Bynder/gathercontent-gather-ui

package.json
tests/Button.js
tests/setup.js

A simple structure for tests. Let me know what you think 😄

Add test structures and tooling

---

.storybook/config.js
lib/CheckToggle/index.js
lib/CheckToggle/styles.scss
lib/NotificationAlert/index.js
lib/NotificationAlert/styles.scss
lib/index.js
stories/index.js
styles/main.scss
tests/CheckToggle.js
tests/NotificationAlert.js

Bringing over a couple of components and refactored the way Bootstrap is imported to maintain the order of styling.

Component extraction: part one

---

.storybook/config.js
.storybook/utils.js
.storybook/webpack.config.js
README.md
lib/CheckToggle/styles.scss
lib/NotificationAlert/styles.scss
package.json
styles/main.scss
styles/settings/typography.scss

Font files requiring an SVG loader need a different kind of loader than regular SVG images to inline... Webpack 🤡

Issue: SVG loading

---

.storybook/config.js
.storybook/utils.js
lib/NotificationAlert/styles.scss
styles/main.scss
styles/settings/typography.scss

Add development stylesheet (dynamically) to use the same font files as the application.

Add typography CSS stylesheet

---

lib/DropdownMenu/styles.scss
lib/DropdownSwitcher/index.js
lib/DropdownSwitcher/styles.scss
lib/index.js
stories/index.js
styles/main.scss

Moved some CSS around. No tests, yet.

Add Dropdown switcher components

---

lib/Button/index.js
tests/Button.js
tests/ProgressButton.js

Not completely ready but wanted to get some visibility on it now. I just need to refactor the styling side of it. A refactoring of the tests are included too 👍 
Thoughts?

Button component refactor

---

lib/Button/index.js
lib/Button/styles.scss
stories/components/Button.js

After refactoring the Button component and with the story structure changes I didn't get a chance to  update the usages of the Button component so they were all broken.
All is fixed now though 👍

Button Stories

---

.eslintrc.json
package.json

Using the same config from our main app here's linting in the ui library.

Add linting

---

stories/components/Modals.js

Fix missing component renaming for the Modal Story in Storybook (Modal.Modal to Modal.Container and so on).

Fix missing component renaming for the Modal Story in Storybook

---

lib/Conversation/Comment.js
lib/Conversation/CommentForm/CommentFormActions.js
lib/Conversation/CommentForm/index.js
lib/Conversation/CommentList.js
lib/Conversation/index.js
lib/Conversation/styles.scss
lib/Person/index.js
stories/components/Conversation.js
tests/Conversation/Comment.js
tests/Conversation/CommentForm/CommentForm.js
tests/Conversation/CommentForm/CommentFormActions.js
tests/Conversation/CommentList.js
tests/Conversation/Conversation.js

During the integration we noticed a few things that had to be fixed. Here are the fixes.
--------------
After this we should patch his package and publish 👍

Conversation Component Integration Changes

---

lib/Field/index.js
lib/FileCard/index.js
lib/FileCard/styles.scss
lib/index.js
package-lock.json
package.json

Minor updates to FileCards and Fields to make the UI in-app play nicely together.

Update FileCard and Fields

---

lib/Field/index.js
lib/Field/styles.scss
stories/components/Field.js

I've removed some opinionated layout components from the Field component so its easier to use.

Field component cleanup

---

lib/Conversation/Comment.js
lib/Conversation/index.js
lib/Field/FieldActions.js
lib/FileCard/index.js
lib/FontAwesomeIcon/index.js
lib/PlanBox/Button.js
tests/Button/ButtonWithTooltip.js
tests/CheckToggle.js
tests/Conversation/CommentList.js
tests/Conversation/Conversation.js
tests/FileCard/index.js
tests/PlanBox/Button.js
tests/PlanBox/index.js
tests/ProgressButton/index.js
tests/SearchInput.js
tests/Table/Heading/index.js
tests/setup.js

- Fixed failing tests for PlanBox
- Fixed most warnings around prop type validation

Fix PlanBox tests and resolve warnings

---

lib/DropdownMenu/styles.scss
lib/StatusIndicator/index.js
lib/StatusIndicator/styles.scss
stories/components/StatusIndicator.js
tests/StatusIndicator/index.js

Add flex to align the components, add an optional description, add `current` and `complete` props

Add some styling changes to the StatusIndicator

---

lib/Avatar/AvatarWithTooltip.js
lib/Avatar/index.js
lib/AvatarGroup/index.js
stories/components/Avatar.js

There have been some breaking changes to this in the past stopping the pillbox text from appearing. This has now been resolved.

Minor Avatar fixes

---

assets/icons/caret.svg
assets/icons/comment.svg
assets/icons/loader.svg
assets/icons/menu.svg
assets/icons/plus.svg
lib/Icon/index.js
lib/Icon/styles.scss
lib/ProgressButton/styles.scss
stories/components/Icons.js
tests/Icon/index.js

We have a couple of new icons defined in the Icon component;
- menu
- loader
I've also cleaned up how we handle the interactive and active states for icons as there are times where we want to use `fill` rather than `stroke`.

Added new icons and cleaned up the stories

---

lib/Button/index.js
tests/Button/index.js

this is useful so we can get the button target for instance

Make Button pass the original onClick event to the clickHandler

---

lib/BoundaryClickWatcher/index.js
lib/Conversation/Comment.js
lib/Conversation/CommentForm/CommentFormActions.js
lib/Conversation/CommentForm/CommentFormInput.js
lib/Conversation/index.js
lib/FileCard/index.js
lib/FileCard/styles.scss
lib/Form/Checkbox/Group.js
lib/Form/Checkbox/index.js
lib/List/ListItem.js
lib/SearchInput/index.js
lib/Table/Heading/index.js
stories/components/FileCard.js
tests/Button/ButtonWithTooltip.js
tests/Button/index.js
tests/Conversation/Comment.js
tests/Conversation/CommentForm/CommentFormActions.js
tests/Conversation/CommentList.js
tests/EditableTextWrapper/index.js
tests/Field/Field.js
tests/Field/FieldAside.js
tests/FileCard/index.js
tests/Form/Checkbox.js
tests/Form/RadioButton.js
tests/Form/RadioButtonOther.js
tests/List/ListItem.js
tests/Modal/ModalFooter.js
tests/Modal/ModalHeader.js
tests/Modal/withModalToggle.js
tests/SearchInput.js

All the details for what this fixes is in #109 👍

FileCard Refactor

---

lib/Guideline/index.js
lib/Guideline/styles.scss
lib/index.js
stories/components/Guideline.js
stories/components/Modals.js
stories/index.js
styles/components/_ui.scss
tests/Guideline/Guideline.js

Here's a new component for the library...the Guideline component 😄

Guideline Component

---

lib/Guideline/styles.scss
stories/base/Base.js
styles/overrides/_modal.scss
styles/settings/_colours.scss

After some review we realised that of the the neutral colours was off. This PR fixes that 👍

Fixed / added neutral colours

---

lib/EditableTextWrapper/index.js
tests/EditableTextWrapper/index.js

Feedback from James, Alice and others in demo

onBlur should submit/call the handler

---

lib/Form/styles.scss

A very minor change to resolve the alignment issues with Radio and Checkbox fields.

Fixed alignment issues with Radios and Checkboxes

---

lib/Guideline/index.js
lib/Guideline/styles.scss
lib/constants.js
lib/index.js
stories/components/Guideline.js
tests/Guideline/Guideline.js
tests/constants.spec.js

This PR adds a few updates, such as;
- animates the body when active
- adds an additional declaration for handling contents and margin bottom
- exposes certain SCSS settings for JS consumption (this is going to be handy in the future)

Updated guideline component

---

lib/FileCard/index.js
lib/FileCard/styles.scss
stories/components/FileCard.js

Feedback applied;
- Fix border-radius issue with wrapper
- Make FileCards 3up & retain the same width and height (uses Row/Col to do this in stories)

FileCard updates

---

styles/bootstrap/_bootstrap.scss
styles/bootstrap/_variable-overrides.scss

Changed gutter size from 30 to 20.

updated gutter config

---

lib/Avatar/README.md
lib/Avatar/styles.scss
lib/Button/styles.scss
lib/DropdownMenu/styles.scss
lib/DropdownSwitcher/README.md
lib/DropdownSwitcher/index.js
lib/DropdownSwitcher/styles.scss
lib/Logo/README.md
lib/Navigation/README.md
lib/Navigation/styles.scss
lib/SectionHeader/README.md
lib/SectionHeader/index.js
lib/SectionHeader/styles.scss
lib/Shortcut/README.md
lib/index.js
stories/components/DropdownSwitcher.js
stories/components/SectionHeader.js
stories/index.js
styles/components/_ui.scss
styles/overrides/_dropdown.scss
styles/settings/_typography.scss
tests/DropdownSwitcher/index.js
tests/SectionHeader/index.js

Various styling fixes which the app seems to break. 
Have also added a SectionHeader component for a standardised site wide title header.

Top bar fixes

---

lib/Field/styles.scss
stories/base/Base.js
stories/components/Field.js
styles/base/_typography.scss

For the `Field` component we have some specific typography styles and some margin alterations to alignment that content with the field label.

Field typography styling

---

lib/DropdownMenu/styles.scss
styles/overrides/_dropdown.scss

Small fix to allow 'active' links in dropdowns. Also prevents dropdowns overflow breaking out of popovers

Dropdown fixes

---

lib/ShortcutTrigger/README.md
lib/ShortcutTrigger/index.js
lib/index.js
package.json
stories/components/ShortcutTrigger.js
stories/index.js
tests/ShortcutTrigger/index.js

This PR adds a new component for firing a function when the user presses a certain key combination. A readme has been added so to get more information, please read that 👍

ShortcutTrigger Component

---

lib/TopBar/styles.scss

(to prevent the flicker on load in firefox)

Add bottom and top position to left and right

---

lib/Avatar/AvatarWithPopover.js
lib/Avatar/styles.scss
stories/components/Avatar.js

Add flexbox to AvatarWithPopover. Makes sure the Avatar is vertically centered in the TopBar within the AvatarGroup

Avatar position

---

lib/StatusIndicator/styles.scss
package.json

This PR resolve a minor issue where the status indicator goes onto 2 lines when it shouldn't.

Fix indicator alignment

---

lib/Form/Checkbox/Input.js
lib/Form/RadioButton/Input.js
lib/StatusIndicator/index.js
lib/TooltipWrapper/index.js
lib/TopBar/TopBarContent.js
stories/components/StatusIndicator.js

This PR resolves a few warnings for certain components where some props aren't actually required etc...

Prop validation updates

---

lib/Avatar/styles.scss
lib/Conversation/CommentForm/styles.scss
lib/Conversation/styles.scss
lib/Person/styles.scss

Weight has been taken out of comments by reducing padding and font sizes.

Changes to comments

---

lib/Button/index.js
lib/EditableTextWrapper/index.js
lib/PageInformation/index.js

Titles make for better usability. So we've added them to certain components.

Add title to some components

---

lib/ExpandingTextArea/README.md
lib/ExpandingTextArea/index.js
lib/Field/index.js
lib/Field/styles.scss
tests/ExpandingTextArea/ExpandingTextArea.js
tests/Field/Field.js

Adding a minRows prop to ExpandingTextArea, and an instructionsPlaceholder prop to Field.

Adding Field and ExpandingTextArea config

---

assets/icons/clock.svg
assets/icons/warning.svg
lib/Icon/index.js
lib/StatusIndicator/index.js
lib/StatusIndicator/styles.scss
stories/components/Icons.js
stories/components/StatusIndicator.js
tests/Icon/Icon.spec.js
tests/StatusIndicator/index.js

Amendments to match design for StatusIndicator and added 2 new Icons. 
Have added an action prop to StatusIndicator to allow for object to show next to label. Have also fixed styling as well as text overflowing

Workflow amends

---

lib/StatusIndicator/styles.scss
lib/TopBar/styles.scss
styles/overrides/_popover.scss
styles/settings/_layout.scss

Cleaned up StatusIndicator variables. 
Use consistent border and box shadow for all popovers

Style tweaks to match design and to make popovers consistent

---

styles/base/_typography.scss

Baby PR, literally just adding a new .hover selector for mark tags

add styles for .hover for mark tags

---

lib/Conversation/Comment.js
lib/Conversation/CommentForm/index.js
lib/Conversation/README.md
lib/Conversation/index.js
lib/ExpandingTextArea/README.md
lib/ExpandingTextArea/index.js
tests/Conversation/Comment.js
tests/Conversation/CommentForm/CommentForm.js
tests/Conversation/Conversation.js
tests/ExpandingTextArea/ExpandingTextArea.js

It's handy to be able to execute a function when the row count changes.

Add onRowCountChange prop function

---

lib/Conversation/Comment.js
lib/Conversation/CommentList.js
lib/Conversation/styles.scss
lib/Person/README.md
lib/Person/index.js
stories/components/Conversation.js
tests/Conversation/Comment.js
tests/Conversation/CommentList.js

I've added confirmation UI when deleting comments. Not much else to say 😄

Delete Confirmation for Comments

---

lib/ExpandingTextArea/index.js
package.json
tests/ExpandingTextArea/ExpandingTextArea.js
yarn.lock

When the user resizes the browser the rows need to recalculate 👍 
I've added some debouncing so this doesn't cause many performance issues.

Fix resize calculations

---

lib/MessageBar/styles.scss

quick one liner, self explanatory!

MessageBar a tags should be underlined

---

lib/TopBar/styles.scss

Just some simple css to subtract the TopBar height from the dropdown height

Issue: Cant access last item in TopBar dropdown 

---

lib/StatusIndicator/styles.scss

Have slightly tweaked the status indicator margins for due date settings and descriptions

Tweak status indicator margins

---

lib/Guideline/index.js
stories/components/Guideline.js
tests/Guideline/Guideline.js

This PR adds the ability for Guidelines to just show titles.

Guideline updates

---

lib/Form/FormInput.js
lib/Guideline/index.js
lib/Tabs/TabsForm.js
lib/Tabs/styles.scss
tests/Form/FormInput.spec.js
tests/Tabs/TabsForm.spec.js

and FormInput, not much else to say!

Adding placeholders to TabsForm

---

lib/List/ListItem.js
lib/List/styles.scss
stories/components/List.js

There's a slight issue here, as every button will have to have pixel values specified due to the discrepancies in icon sizing. Would love a chat about how we can make this applicable across every icon, but it may be that we have to size as and when.

Updating icon hit area with pixel padding.

---

lib/EditableTextWrapper/index.js
tests/EditableTextWrapper/index.js

Instead of just the pencil icon click

EditableTextWrapper now goes into the editing view on text click

---

lib/Tabs/styles.scss

Updating padding for active and none-active structure tabs

---

lib/Field/styles.scss
yarn.lock

A small PR to add hover transitions for field asides

Field Aside Changes

---

lib/BoundaryClickWatcher/README.md
lib/BoundaryClickWatcher/index.js
lib/Conversation/styles.scss
lib/FileCard/styles.scss
lib/Form/styles.scss
tests/BoundaryClickWatcher/BoundaryClickWatcher.spec.js

I've just added some mouseEnter and MouseLeave props to it. Maybe we should just rename it BoundaryWatcher!
Also some minor styling changes for parent hover stuff

New BoundaryClickWatcher mouse events

---

lib/Conversation/index.js

adding className to Conversation

---

lib/Avatar/index.js
lib/Avatar/styles.scss
lib/SearchDropdown/index.js
lib/UserList/index.js
lib/UserList/styles.scss

Just some minor styling changes, and adding focusOnMount prop to SearchDropdown

Avatar and UserList tweaks

---

lib/Button/styles.scss
lib/Conversation/Comment.js
lib/Conversation/CommentForm/CommentFormActions.js
lib/Conversation/CommentForm/index.js
lib/Conversation/CommentForm/styles.scss
lib/Conversation/index.js
stories/components/Conversation.js
tests/Conversation/Comment.js
tests/Conversation/CommentForm/CommentForm.js
tests/Conversation/CommentForm/CommentFormActions.js

This PR updates the way we edit comments for conversations. It improves the editing experience.

Inline Comment Edits

---

lib/DueDatePicker/DueDateButton.js
lib/DueDatePicker/styles.scss
tests/DueDatePicker/DueDateButton.js

Remove clock icon from set due date

---

lib/StatusIndicator/index.js

Exactly what it says on the tin

Add title attribute to StatusIndicator title

---

styles/overrides/_modal.scss

scss override to hide the close button on modals should we want to

---

lib/Shortcut/styles.scss

Adding shortcut styles for super and sub script

---

lib/Dropdown/index.js
lib/DueDatePicker/DueDateButton.js
lib/DueDatePicker/DueDateHeader.js
lib/DueDatePicker/DueDateLabel.js
lib/DueDatePicker/index.js
lib/DueDatePicker/styles.scss
styles/overrides/_daypicker.scss
tests/DueDatePicker/DueDateButton.js
tests/DueDatePicker/DueDateHeader.js
tests/DueDatePicker/DueDateLabel.js
tests/DueDatePicker/index.js

Use new Dropdown component for DueDates this fixes a strange positioning bug which shifts the dropdown when a date is changed on DueDateLabel
Fixes some styling issues.
Fixes an issue where the saved due date (sent via prop) doesn’t update the state.selectedDay

Due Date Amendments

---

lib/DueDatePicker/index.js

Close DueDatePicker when we remove the due date

DueDate bug fix

---

.travis.yml
lib/BlankSlate/README.md
lib/BlankSlate/index.js
lib/BlankSlate/styles.scss
lib/Conversation/index.js
lib/Conversation/styles.scss
lib/Form/Checkbox/Group.js
lib/Form/Checkbox/Input.js
lib/Form/Label/index.js
lib/Form/RadioButton/Group.js
lib/Form/RadioButton/Input.js
lib/Form/RadioButton/Other.js
lib/Form/styles.scss
tests/BlankSlate/index.js
tests/Conversation/Conversation.js
tests/Form/Label.js
tests/Form/RadioButtonOther.js

A few little things:
- Choice inputs can how have a disabled prop passed to them
- Conversation can now have a resolved prop passed to it
- BlankSlate can now be provided with a customSVG

A few bits

---

lib/CheckToggle/index.js
lib/CheckToggle/styles.scss
stories/components/CheckToggle.js
tests/CheckToggle/CheckToggle.js

And a displayChecked prop to give us a lovely green background when they're checked

Adding a small version for CheckToggle

---

lib/Dropdown/DropdownAction.js
lib/DropdownMenu/index.js
lib/DropdownMenu/styles.scss
lib/TopBar/styles.scss
stories/components/DropdownMenu.js
tests/DropdownMenu/index.js

- Send event to Dropdown.Action callback
- Add disabled prop to DropdownMenu
- Add a bottom margin to .top-bar__drop-down (stops it going over the status bar)

Ux issue amends

---

lib/BlankSlate/index.js
lib/Dropdown/styles.scss

Fixing a prop type error for CustomSVGs in BlankSlate
Adding a link style class for Dropdown.Actions

Couple of baby fixes

---

styles/base/_typography.scss

Just changing the border colour

Minor style change to blockquotes

---

lib/ConversationContext/README.md
lib/ConversationContext/index.js
lib/ConversationContext/styles.scss
lib/index.js
stories/components/ConversationContext.js
stories/index.js
styles/components/_ui.scss
tests/ConversationContext/ConversationContext.js

A new component to display a conversation and its context

A new ConversationContext component

---

lib/Avatar/index.js
lib/Avatar/styles.scss
lib/ItemRow/index.js
lib/ItemRow/styles.scss
lib/List/index.js
lib/List/styles.scss
lib/StatusIndicator/index.js
lib/StatusIndicator/styles.scss
lib/helpers/index.js
stories/components/Avatar.js
stories/components/ItemRow.js
stories/components/List.js
stories/components/StatusIndicator.js
stories/index.js
tests/ItemRow/ItemRow.spec.js
tests/List/List.spec.js
tests/StatusIndicator/StatusIndicator.spec.js

This PR adds styles for boarded lists and stacked item rows.
There is a issue with bordered lists when having lists within lists. We can resolve this later.

Item row updates

---

lib/Dropdown/DropdownAction.js
lib/Dropdown/styles.scss
stories/components/Dropdown.js
styles/overrides/_tooltip.scss
tests/Dropdown/DropdownAction.spec.js

New Dropdown.Action modifiers

---

lib/Form/Checkbox/Group.js
lib/Form/Label/index.js
lib/Form/RadioButton/Group.js
lib/Form/styles.scss
stories/components/Form.js
tests/Form/Label.spec.js

This PR adds a modifier to hint colouring to labels.

Add hint modifier to form labels

---

lib/ConversationContext/index.js
lib/ConversationContext/styles.scss
tests/ConversationContext/ConversationContext.js

add resolveConversation to ConversationContext

---

.eslintrc.json
.gitignore
lib/List/styles.scss
stories/components/List.js
yarn.lock

When using links correctly in the list component it styles everything like the default styling. This PR fixes that.

List link styling

---

lib/UserList/CurrentUserList.js

No need to pass isOffline to <Avatar> from CurrentUserList

Don’t pass isOffline to <Avatar>

---

lib/TopBar/styles.scss

We needed different padding for top bar actions and item settings button

Fix top bar action padding issue

---

lib/DropdownMenu/index.js
lib/Table/Heading/index.js
tests/BlankSlate/index.js
tests/Button/index.js
tests/Conversation/Comment.js
tests/Conversation/CommentForm/CommentForm.js
tests/Conversation/CommentForm/CommentFormActions.js
tests/Dropdown/Dropdown.spec.js
tests/DropdownMenu/index.js
tests/EditableTextWrapper/index.js
tests/Form/RadioButtonOther.js
tests/Modal/withModalToggle.js
tests/Navigation/index.js
tests/ProgressButton/index.js
tests/StatusIndicator/StatusIndicator.spec.js
tests/Table/Heading/index.js
tests/UserList/CurrentUserList.js
tests/UserList/index.js

We should now have a stunning suite of tests passing for react 16 🎉 🎉 
Most errors were caused by Enzyme 3 updates to how mount works, and how components are now updated.
related issues:
https://github.com/airbnb/enzyme/issues/1153 
https://github.com/airbnb/enzyme/issues/1253
https://github.com/airbnb/enzyme/issues/1177

Fix all the tests!

---

lib/DropdownMenu/index.js

Dont pass the wrong prop to Avatar

---

lib/Conversation/Comment.js
stories/components/Conversation.js
tests/Conversation/Comment.js

As the title says, slightly smarter mention highlighting!

Only highlight mentions that exist in the users prop

---

lib/Conversation/Comment.js
lib/Conversation/index.js
lib/Conversation/styles.scss
lib/ConversationContext/index.js
stories/components/Conversation.js
tests/Conversation/Comment.js
tests/Conversation/Conversation.js

adding this prop for some more control over users being able to resolve a conversation

userCanResolve prop

---

lib/Modal/styles.scss
stories/components/Modals.js

There is an issue where columns don't collapse due to flex box and widths on modals are always applied.

Fix modals on mobile

---

lib/HTMLTable/index.js
lib/HTMLTable/styles.scss
lib/index.js
stories/components/HTMLTable.js
stories/index.js
styles/components/_ui.scss

Added some styles for a simple html table. Provides <table> tag only

Add HTML table styles

---

lib/TooltipWrapper/index.js
tests/TooltipWrapper/index.js

Adding a class to the span we add
Will accept and object for tooltipText

Minor tooltip changes

---

lib/StatusIndicator/index.js
lib/StatusIndicator/styles.scss
tests/StatusIndicator/StatusIndicator.spec.js

made a booboo with some styling, causing the status text to be prematurely cut off, this fixes it!

fixing broken StatusIndicator styling

---

lib/Field/styles.scss

One liner - just removing a font-family

Field styles

---

lib/HTMLTable/styles.scss

Removed line height for HTML table

HTMLTable line-height

---

lib/Form/Checkbox/Group.js
lib/Form/RadioButton/Group.js
package-lock.json
tests/Form/CheckboxGroup.js
tests/Form/RadioButtonGroup.js

This PR changes how we add and remove options from state in input groups to give us more control in the consuming app.

Input group changes

---

lib/FileCard/FileCardPreview.js
lib/FileCard/index.js
lib/FileCard/styles.scss
stories/components/FileCard.js
tests/FileCard/FileCardPreview.spec.js
tests/FileCard/index.spec.js

This PR adds a better way for us to manage loading states. Because we didn't have this I had to refactor some things like moving the preview aspect of the component into another component.
Test it locally to see what it looks like 👍

added better processing and loading states

---

lib/List/ListItem.js
tests/List/ListItem.spec.js

Does what it says on the tin 😄

Add toggle prop function to list items

---

lib/Search/SearchBoundaryListener.js
lib/Search/SearchInput.js
lib/Search/ToggleFilter.js
lib/Search/index.js
lib/Search/styles.scss
stories/components/TopBar.js
tests/Search/ToggleFilter.spec.js

A few mainly stylistic changes to search

---

lib/Search/styles.scss

Changed linear transitions to cubic-bezier taking inspiration from material design guidelines.

Tweaks to search bar animation

---

lib/Search/styles.scss

Small PR, just as the title says
Beautiful greyness

Make cross icon grey in Search

---

lib/Form/FormInput.js
lib/Tabs/TabsForm.js
tests/Form/FormInput.spec.js
tests/Tabs/TabsForm.spec.js

add onInputChange prop to TabsForm and FormInput

---

lib/ShortcutTrigger/index.js
tests/ShortcutTrigger/index.js

Small pr, just as the title says :)

Pass the event onShortCutTrigger

---

lib/TooltipWrapper/index.js
tests/TooltipWrapper/index.js

As the title says, we already pass the className prop to the tooltip itself

add wrapperClassName prop to TooltipWrapper

---

lib/ProgressButton/index.js
lib/TopBar/TopBarCell.js
tests/ProgressButton/index.js
tests/TopBar/TopBarCell.js

Simple
Added a disabled prop to ProgressButton too

Add className prop to TopBarCell

---

lib/Navigation/styles.scss

as the title says, just styling

Minor changes to navigation--tabs

---

lib/PageInformation/index.js
lib/PageInformation/styles.scss
styles/tools/_mixins.scss

Removed the max width from the page information component as it isn't required. Also added some more responsive mixins. They were helpful when I was trying to fix something in the app 👍

Page information changes

---

lib/Card/index.js
lib/Card/styles.scss
lib/CollectionsTable/CollectionsTableRow.js
lib/CollectionsTable/styles.scss
stories/components/CollectionsTable/CollectionsTable.js
stories/components/CollectionsTable/OtherBodyRowExample.js
styles/helpers/_interactive.scss
styles/main.scss
tests/CollectionsTable/CollectionsTableRow.spec.js

Couple of styling tweaks, adding a selected style to Card and CollectionsRable and making FileCards work within CollectionsTable

Styling changes to CollectionsTable and Card

---

styles/overrides/_popover.scss
styles/overrides/_tooltip.scss

Our good friend font-smoothing again.
Maybe this will be the final cull

Remove font smoothing for non-retina

---

lib/DueDatePicker/styles.scss
lib/StatusIndicator/styles.scss
styles/helpers/_colours.scss

Make sure its always red and the right font-weight

fix overdue due date styling

---

lib/Conversation/styles.scss

Add a background variable to unactive conversations

Comment bg

---

lib/FormModal/index.js

By passing onHide to Modal.Container

Fix the little x on FormModal

---

lib/Form/FormInput.js

Make sure the value prop isnt included in 'rest'

fix FormInput

---

lib/CollectionsTable/styles.scss
lib/FinderNavigation/FinderItem.js
lib/FinderNavigation/styles.scss
stories/components/FinderNavigation.js
stories/index.js
tests/FinderNavigation/FinderItem.spec.js

- Adding selected prop & styles for FinderNavigationItems
- Stopping the wiggle for selected CollectionsTableItems
- Resurrecting the indentation styles loop and using it in FinderNavigation

Style improvements for FinderNavigation and CollectionsTable

---

lib/Modal/Modal.js
lib/Modal/styles.scss
stories/components/Modals.js
styles/overrides/_modal.scss

Pretty much as the title says. Now we can have a (near) full screen modal

Full screen width modal

---

lib/FinderNavigation/FinderItem.js
lib/FinderNavigation/FinderItemContent.js
lib/FinderNavigation/styles.scss

Adding some reordering styles to FinderNavigation

---

lib/CollectionsTable/styles.scss

Adding a quick selector to disable all selected items in the table

---

lib/BlankSlate/styles.scss

Some styling for links in BlankSlates

---

lib/FinderNavigation/FinderGroup.js
lib/FinderNavigation/FinderItemContent.js
lib/FinderNavigation/FinderItemSettings.js
lib/FinderNavigation/styles.scss
tests/FinderNavigation/FinderGroup.spec.js

There are a number of cases where hover states aren't behaving as expected;
- settings are hiding when hovering over dropdowns
- icon paths aren't highlighting correctly
As well as this I have also brought it inline with BEM a little more. We were using modifiers when classes were elements.

Finder panel hover fixes

---

lib/FinderNavigation/styles.scss
stories/components/FinderNavigation.js

Fix finder item styling

---

lib/FinderNavigation/FinderItemContent.js
lib/FinderNavigation/styles.scss
package.json

- Adds `hidden` prop to <FinderItemContent /> which transitions it's height to 0px
- Adds my name to `package.json`, I'm here to stay!
Related to https://github.com/gathercontent/app/pull/1578

Adds `hidden` prop to <FinderItemContent />

---

lib/FinderNavigation/README.md
lib/FinderNavigation/styles.scss

- Adds styles to the item link
Related to https://github.com/gathercontent/app/pull/1581

Adds styles to the item link

---

lib/BlankSlate/index.js

Add className prop to BlankSlate

---

lib/FinderNavigation/styles.scss

Fix styling for finder group titles

Change class modifiers for finder

---

lib/FinderNavigation/styles.scss
stories/components/FinderNavigation.js

- Change icon colours for consistency in finder panel
- Fix nested spacing to match designs

Update finder nav icon colours and indentation of folders

---

lib/FinderNavigation/styles.scss

exactly as the title says, easy peasy

Change the finder dropdown style

---

lib/ConfirmationModal/index.js
lib/DueDatePicker/DueDateButton.js
lib/DueDatePicker/index.js
lib/Modal/Modal.js
lib/Modal/ModalFooter.js
lib/Modal/ModalHeader.js
lib/Modal/styles.scss
lib/StatusIndicator/index.js
lib/StatusIndicator/styles.scss
stories/components/Modals.js
stories/components/StatusIndicator.js
styles/overrides/_modal.scss
tests/StatusIndicator/StatusIndicator.spec.js

PR to add/fix the following;
- Allow props.children to define custom text for `DueDatePicker` / `DueDateButton`
- Allow dropdowns to work with `autoPosition` set to true within fixed elements like Modals
- Add additional modifiers to status indicators & modals (highlight and row)

Confirmation modal date picker updates

---

lib/BlankSlate/index.js
lib/Button/styles.scss
lib/Dropdown/DropdownAction.js
lib/Dropdown/README.md
lib/Dropdown/styles.scss
lib/FinderNavigation/styles.scss
tests/Dropdown/DropdownAction.spec.js

Add disabled prop to DropdownAction and styles

---

lib/FinderNavigation/styles.scss

Fix issue where closed folders have more height caused by hidden childs margins

Fix finder closed folder heights

---

lib/Dropdown/DropdownAction.js
lib/Dropdown/DropdownContent.js
lib/Dropdown/styles.scss
lib/StatusIndicator/styles.scss
stories/components/Dropdown.js

Added some styling update when using StatusIndicator within a Dropdown.Action 👍 
I also added/fixed a couple of dropdown related issues like not being able to get a full dropdown wrapper and recently added margin clears doing too much.

Dropdown updates

---

lib/CollectionsTable/styles.scss
styles/base/_forms.scss

Adding some easy styles to CollectionTable inputs.
I've added a style for all inputs to remove the outline on focus, as we seem to do that for every single one anyway!

Adding styling for CollectionTable inputs

---

lib/FinderNavigation/styles.scss

Another small one, just as it says above

Styles for FinderNavigation.Settings colour

---

lib/Dropdown/styles.scss

Matches designs to slightly increase size of dropdown status indicators.

Dropdown status indicator

---

README.md
lib/SelectionBar/README.md
lib/SelectionBar/SelectionBarDivider.js
lib/SelectionBar/index.js
lib/SelectionBar/styles.scss
lib/TooltipWrapper/README.md
lib/TooltipWrapper/index.js
lib/TooltipWrapper/styles.scss
styles/components/_ui.scss
tests/SelectionBar/SelectionBarDivider.spec.js
tests/TooltipWrapper/index.js

- Adds docs for deploying the library to NPM
- Adds `<SelectionBarDivider>` component
- Adds `clickable` prop to `<TooltipWrapper>` to change the cursor to a pointer
- Adds/updates docs and tests

Feature/content hub/update selection bar

---

lib/SelectionBar/SelectionBarCancel.js
lib/SelectionBar/styles.scss
tests/SelectionBar/SelectionBarCancel.spec.js

Pretty much as the title says, instead of just some text, its now a handy button

Add a cancel button to SelectionBarCancel

---

lib/FeatureList/styles.scss
lib/Pricing/styles.scss
lib/PricingPlan/styles.scss
lib/SectionFeature/styles.scss
stories/components/Pricing.js
styles/base/_typography.scss

This PR contains some feedback changes to some pricing components.

Pricing component feedback

---

lib/Pricing/PricingText.js
lib/PricingPlan/PricingPlan.js
lib/index.js
stories/components/Pricing.js

We wanted commas in the price text...now we have it 😄

Add PricingText component

---

lib/FeatureList/README.md
lib/SectionFeature/README.md
lib/SectionFeature/SectionFeature.js
lib/SectionFeature/styles.scss
stories/components/Pricing.js

This PR adds a extend modifier for the section feature component.

Add a modifier for SectionFeature

---

lib/CollectionsTable/styles.scss

Stop CollectionsTableRows from wiggling when selected

---

lib/ConfirmationDropdown/ConfirmationDropdownContent.js
tests/ConfirmationDropdown/ConfirmationDropdownContent.spec.js

Oof you might need to tackle this beast of a pr in stages

Make ConfirmationDropdown confirm button blue

---

lib/CollectionsTable/index.js
lib/CollectionsTable/styles.scss

As the title says, another little one

Make CollectionsTable headings and cell padding consistent

---

lib/Conversation/index.js
lib/Conversation/styles.scss
lib/SectionFeature/styles.scss
stories/components/Conversation.js
stories/components/Pricing.js
styles/helpers/_colours.scss

Resolved conversations weren't interactive but the text was still blue 🤔 
This fixes that and makes the UI much clearer 👍

Improve the UX for resolving

---

lib/UserSearch/index.js

Just realised the component should do this
There's always one little thing I end up missing out!

Make sure we clear the selected users on toggle

---

lib/Pricing/styles.scss
lib/SectionFeature/README.md
lib/SectionFeature/SectionFeature.js
lib/SectionFeature/styles.scss

The section feature shouldn't be setting the line-height the way it is and at the same time as that I have added a new modifier so we can increase the size of the first paragraph within the component.
Before this as always the case but we need cases where that doesn't happen.

Fixed line-height and added new modifier

---

lib/Conversation/index.js
lib/Conversation/styles.scss
stories/components/Conversation.js
tests/Conversation/Conversation.js

This PR adds the props and UI for undoing a resolved conversation 👍

Undo conversations UI

---

styles/overrides/_helpers.scss

Joins the hide small and medium ones, nothing more to it!

Hide large utility class

---

lib/Button/styles.scss
lib/ConfirmationModal/index.js

And the ability to disable a confirmation modal button

New white link button style

---

lib/Avatar/styles.scss
lib/BlankSlate/styles.scss
lib/Button/styles.scss
lib/Dropdown/styles.scss
lib/Navigation/styles.scss
stories/base/Base.js
styles/base/_typography.scss
styles/generic/_global.scss
styles/generic/_normalize.scss
styles/settings/_colours.scss

With direction from design, we've now updated the colours across the app to match new designs.

Update colour varibles 

---

lib/UserSearch/styles.scss

Does what it says on the tin ;)

Change a few styles for UserSearch to match designs

---

lib/Button/styles.scss
lib/CopyToClipboard/index.js
lib/InputWithButton/README.md
lib/InputWithButton/index.js
lib/InputWithButton/styles.scss
lib/index.js
stories/components/InputWithButton.js
stories/index.js
styles/components/_ui.scss
tests/InputWithButton/InputWithButton.spec.js

- Creates a component that displays a text input with a button appended to it.
- The button onClick callback passes the input element as an argument, so you can manipulate it (eg. copy to clipboard).

Feature/InputWithButton (Copy To Clipboard)

---

.travis.yml

Make travis use node 10

---

lib/images/ImageLoader/README.md
lib/images/ImageLoader/index.js
lib/images/ImageLoader/styles.scss
stories/components/Modals.js

`<ImageLoader />` used to animate between loading and showing. It was broken between apply feedback so I've cleared up the conditional logic for styles and made the styles apply to the container.

Fix ImageLoader animations

---

.travis.yml
README.md

So this should give us some lovely auto deployments, see docs here: https://docs.travis-ci.com/user/deployment/npm/

Travis npm publishing

---

lib/MentionsForm/MentionsFormActions.js
lib/MentionsForm/MentionsFormInput.js
lib/MentionsForm/index.js
lib/UserSearch/index.js
lib/constants.js
lib/helpers.js
tests/MentionsForm/MentionsForm.test.js
tests/MentionsForm/MentionsFormActions.test.js

Little change so we have the option to display the amount of mentions on the mention form

MentionForm feedback

---

pull_request_template.md

- Modifies app PR template to suit gather-ui

Adds PR Template

---

lib/Conversation/README.md
lib/Conversation/index.js
lib/Conversation/styles.scss
stories/components/Conversation.js
tests/Conversation/Conversation.js

A prop has been added so you can now pass in an icon name and it will display it in the corner of a conversation.
https://projects.invisionapp.com/share/N7RZGS5A9ET#/screens/363198154
`Conversation/index.js`
`stories/Conversation.js` (A Simple Conversation has an icon)

Icon in header of Conversation

---

lib/Dropdown/DropdownTrigger.js
lib/Dropdown/README.md
lib/Dropdown/index.js
lib/Figure/styles.scss
lib/Form/FormFooter.js
lib/Form/styles.scss
lib/index.js
stories/components/Form.js
tests/Dropdown/Dropdown.spec.js

Some fixes to enable figure + dropdown + form usages.
When using a combo of figure, dropdown and form components together we run into various issues. These range from being able to hide the dropdown after completing a task to not being able to click on the form.

Figure & Dropdown Fixes

---

lib/Figure/styles.scss

fix assets styling

---

lib/Breadcrumb/styles.scss
stories/components/Breadcrumb.js
styles/generic/_global.scss
styles/settings/_typography.scss

Build out the breadcrumb component.

Breadcrumb

---

lib/Breadcrumb/BreadcrumbItem.js
lib/Breadcrumb/index.js
lib/Breadcrumb/styles.scss
stories/components/Breadcrumb.js

Spread props to breadcrumb component. And added mobile style (simple hide and show).

Breadcrumb updates

---

lib/Button/styles.scss
lib/Form/FormInput.js
lib/Form/styles.scss
lib/InputWithButton/README.md
lib/InputWithButton/index.js
lib/InputWithButton/styles.scss
stories/base/Base.js
stories/components/Form.js
stories/components/InputWithButton.js
tests/Form/FormInput.spec.js
tests/InputWithButton/InputWithButton.spec.js

A couple of other form specific styles, and I've tweaked InputWithButton to have a small and large version.
I could go way further down this rabbit hole, but i think its probably best to have a cross guild chat to resolve most of the basic element core styling issues that we have!

Add some default FormInput styles

---

lib/EditableTextWrapper/index.js

Make the onstart/stop functions not required with defaults

---

lib/DueDatePicker/DueDateButton.js

Updates `<DueDateButton />` to always render its children if they are present.
https://github.com/gathercontent/app/pull/1918

Updates DueDateButton to render its children if it has any

---

lib/Button/styles.scss

Remove the padding here, we add it in the item list anyway, and I want to use this class for the overdue filter button.

Remove excess padding, we override this in old item list anyway

---

lib/Pill/README.md
lib/Pill/index.js
lib/Pill/styles.scss
lib/index.js
stories/components/Pill.js
stories/index.js
styles/components/_ui.scss
tests/Pill/index.js

A Pill component has been created to be used in the filter redesign. 
https://app.goabstract.com/share/0deb63c9-cb4b-4077-9c41-a9d312b3f17b?collectionLayerId=6b7fbfe7-6a55-48d1-a30d-a187c7a4134c&present=true
`lib/Pill/index.js`

 Pill Component

---

lib/TopBar/styles.scss

This is a real baby fix. Just making sure we account for any notification height in the topbar dropdowns

Account for notification height for topbar notifications

---

lib/Button/ButtonWithIcon.js
lib/Button/styles.scss
lib/TopBar/styles.scss
stories/components/Button.js
tests/Button/ButtonWithIcon.spec.js
yarn.lock

Adds a `dropdownContent` prop to `ButtonWithIcon` that lets you render a lovely dropdown for the icon.
http://g.recordit.co/4IULIHFz6T.gif
`lib/Button/ButtonWithIcon.js`

Add dropdown option to ButtonWithIcon

---

.storybook/config.js
lib/FolderRow/FolderRow.js
lib/FolderRow/stories/FolderRowStory.js
lib/FolderRow/styles.scss
lib/ItemRow/styles.scss
stories/webapp/hierarchy/HierarchyItemRow.js
stories/webapp/hierarchy/HierarchyStory.js

This PR improves the toggle for `FolderRow`s 👍 
Here's a GIF: https://cl.ly/c136f5bc7809

Improve folder row toggle

---

lib/FolderRow/FolderRow.js

A small PR to add a title prop to the folder row toggle.

adding title to folder row toggle

---

lib/StatusIndicator/index.js

Spread props so we can get test ids for testing!

---

lib/Form/FormInput.js

Make sure errorMessage has the correct proptype

---

package.json
tests/setup.js
yarn.lock

We'd like to use react-testing library in Gather-UI
Adding it into here shouldn't be much of a hassle because we already use Jest everywhere. so it's just a case of installing the correct packages.

Adding react-testing-library

---

lib/FolderRow/FolderRow.js
lib/FolderRow/styles.scss
stories/webapp/hierarchy/FolderRow/HierarchyFolderRowActions.js
stories/webapp/hierarchy/FolderRow/HierarchyFolderRowForm.js
stories/webapp/hierarchy/FolderRow/NewHierarchyFolderRow.js
stories/webapp/hierarchy/HierarchyCollection.js
stories/webapp/hierarchy/HierarchyFolderRow.js
stories/webapp/hierarchy/HierarchyItemRow.js
stories/webapp/hierarchy/HierarchyStory.js
stories/webapp/hierarchy/shared/HierarchyNameInput.js

This PR refactors a view things in the hierarchy web app story to make it more composable and readable for future work.
It also adds the state where required to create an experience where we can create folders in `gather-ui`.

Add folder

---

lib/SelectedObjectsProvider/index.js
stories/webapp/hierarchy/HierarchyCollection.js
stories/webapp/hierarchy/HierarchyFolderRow.js

pairing feedback

---

lib/ProgressButton/index.js

add classname prop to progress button

---

lib/Avatar/AvatarGroup/index.js
lib/Avatar/AvatarGroup/styles.scss
stories/webapp/hierarchy/HierarchyItemRow.js
styles/helpers/_selected.scss

@DavidHollins6 and I paired up on applying some selected context to the hierarchy view and realised that we were experiencing issues with performance due to over rendering and rows moving about when being interacted with.
This PR fixes those issues 👍

Fix heights for hierarchy view

---

.babelrc
.eslintrc.json
config.js
package.json
stories/webapp/hierarchy/HierarchyStory.js
yarn.lock

Module resolver makes finding modules easier 👍 
This will rock our worlds in the coming months etc...

Add babel module resolve

---

lib/EditableTextWrapper/styles.scss

remove width

---

lib/FolderRow/FolderRow.js
lib/FolderRow/FolderRowAction.js
lib/FolderRow/FolderRowAside.js
lib/FolderRow/FolderRowCell.js
lib/FolderRow/FolderRowContents.js
lib/FolderRow/FolderRowInner.js
lib/FolderRow/FolderRowName.js
lib/FolderRow/index.js
lib/FolderRow/stories/FolderRowStory.js
lib/FolderRow/styles.scss
lib/Windowing/InViewList.js
lib/Windowing/InViewListItem.js
lib/Windowing/WindowingProvider.js
lib/Windowing/stories/WindowingStory.js
lib/Windowing/tests/WindowingProvider.spec.js
lib/index.js
stories/webapp/hierarchy/FolderRow/HierarchyFolderRowActions.js
stories/webapp/hierarchy/HierarchyCollection.js
stories/webapp/hierarchy/HierarchyFolderRow.js
stories/webapp/hierarchy/HierarchyItemRow.js
stories/webapp/hierarchy/HierarchyStory.js
stories/webapp/hierarchy/data.js
tests/FolderRow/FolderRow.spec.js

This PR contains some refactoring before tackling some new windowing challenges.

Pre hierarchy windowing refactors

---

lib/Avatar/AvatarGroup/styles.scss
lib/Logo/index.js

As well as a url string, I wanted to be able to pass an imported SVG to display in the Logo component. This lets me do just that.
Also adding a max-height to the AvatarGroup dropdown, since if theres a load of Avatars it can easily go off screen.

Accept an imported svg in Logo

---

README.md

Adds docs for the `yarn link react` command

Adds docs for the yarn link react command

---

lib/FolderRow/FolderRow.js
lib/Windowing/Windowing.js
lib/Windowing/WindowingItem.js
stories/webapp/hierarchy/HierarchyFolderRow.js
stories/webapp/hierarchy/ItemRow/HierarchyItemRow.js
stories/webapp/hierarchy/shared/HierarchyNameInput.js

This fixes various prop type warnings that happen with windowing.

Fixing prop type errors for windowing

---

pull_request_template.md

Updates the PR template inline with decisions made here https://github.com/gathercontent/app/pull/2124

Updates the PR template

---

stories/webapp/hierarchy/HierarchyFolderRow.js
stories/webapp/hierarchy/HierarchyStory.js
stories/webapp/hierarchy/ItemRow/HierarchyItemRow.js

We accidentally broke the hierarchy story by not using a fixed height. I also add some memo for performance.

Hotfix the hierarchy story

---

lib/Conversation/Comment.js

check for author existing

---

lib/FolderRow/FolderRowActions.js
lib/FolderRow/index.js
lib/FolderRow/styles.scss
stories/webapp/hierarchy/FolderRow/HierarchyFolderRowActions.js

The actions should zoom in like they do on assets for the preview.

Adding animation to hovering over a folder row

---

lib/FolderRow/FolderRowCell.js
lib/FolderRow/styles.scss
lib/Hierarchy/styles.scss
stories/webapp/hierarchy/ItemRow/HierarchyItemRow.js
stories/webapp/hierarchy/shared/HierarchyNameInput.js
styles/components/_ui.scss

This includes multiple styling fixes that came as feedback to the hierarchy. They are originally done inside storybook and will be ported to the app soon.

Various styling fixes for hierarchy

---

lib/FolderRow/FolderRowName.js
lib/FolderRow/styles.scss

This PR fixes the following: 
- Background colour on folder when opened
- Icon on folder when opened

Hierarchy folder style fixes

---

lib/DnD/stories/DnDStory.js
lib/DnD/stories/FolderDndMock.js

When we refactored the folder row we neglected to update the Drag And Drop story, this fixes that!
`lib/DnD/stories/FolderDndMock.js`

Fixing DnD story

---

lib/Button/styles.scss
styles/settings/_colours.scss

This PR updates our button styles to inject a little more personality into our app, as well as making them clearer call to actions through increasing the font-weight.
N/A
N/A
There's only two file changes.
N/A

Button updates

---

lib/Button/styles.scss

Reverts gathercontent/gather-ui#601

Revert "Fixing previous styles"

---

lib/Button/styles.scss
styles/settings/_colours.scss

Reverts gathercontent/gather-ui#600

Revert "Button updates"

---

lib/ConfirmationModal/index.js

pretty much as the title says!

Allow props to control the ProgressButton in ConfirmationModal

---

lib/FinderNavigation/FinderItemContent.js

We would like to pass some other props to this lovely div. This just adds in the `rest`. Simples!

Adding a rest prop to finderItemContent

---

lib/ExpandingTextArea/index.js
lib/ExpandingTextArea/styles.scss
stories/components/ExpandingTextArea.js

Just like our FormInput components ExpandingTextAreas now have the ability to show an error state and an error message.

Add error messages to ExpandingTextArea

---

styles/helpers/_layout.scss

I goofed when I originally made this helper. Every single selector would have a full border, this fixes it now!
I've just added a new position helper too!

Fix border helper class

---

lib/Conversation/CommentForm/CommentFormActions.js

Changed conversation button copy from Send to Comment.
A simple button copy change to more accurately represent the action being made in conversations.

Conversation button copy update

---

lib/ItemRow/styles.scss

The background colour is already white. But now I set it for the previews

Item row background colour

---

lib/Notification/styles.scss
stories/components/Notification.js

We're missing purple notifications.

Add tease notification level

---

lib/Notification/styles.scss

Baby PR here, just some requested changes for the 'teaser' notification

Styling changes for teaser notifications

---

styles/helpers/_layout.scss

Just a nice new helper class to set the opacity of something.
This seems bigger because prettier had it's way with it. The only new thing is the opacity helper.

Creating a helper for opacity

---

styles/helpers/_selected.scss

> 2px dashed border is ridiculous, lets make it 1px
- @p34ks

Decrease border size of selected parent rows from 2px to 1px

---

styles/helpers/_disabled.scss
styles/helpers/_selected.scss

We need to remove pointer events from things that are considered disabled. This adds that!
`https://github.com/gathercontent/app/pull/2535`

DnD Disabled styles

---

lib/PillInput/PillInput.js
lib/PillInput/tests/PillInput.spec.js

Adds `initialPills` prop to `<PillInput />` component
Also adds a `.exportedPropTypes` method to the component, so you can use the PropTypes elsewhere - bit of a departure here, so let me know what you think! [Example usage here](https://github.com/gathercontent/app/pull/2544/files#diff-3653696f50026049226168c8053d7b50R136)

Update/Adds initiallPills prop to PillInput Component

---

lib/SelectionBar/SelectionBarInformation.js

Really simple this, the prop type for one of the new SelectionBar components was a bit wrong. This fixes it!

SelectionBar prop type

---

styles/helpers/_interactive.scss

add pointer events helper class

---

lib/ConfirmationDropdown/ConfirmationDropdownContent.js
lib/ConfirmationDropdown/README.md
lib/ConfirmationDropdown/styles.scss

As the title says, small little change

Add action tooltip prop to ConfirmationDropdown

---

lib/DismissiblePrompt/README.md
lib/DismissiblePrompt/index.js
lib/DismissiblePrompt/stories/DismissiblePromptStory.js
lib/DismissiblePrompt/styles.scss
lib/index.js
stories/index.js
styles/components/_ui.scss
tests/DismissiblePrompt/DismissiblePrompt.spec.js

This is just adding a simple component to allow us to show dismissible prompts around the app. Nothing clever going on, it's mainly so we don't have styling clogging the app!

add a new DismissablePrompt component

---

lib/Icon/index.js

Turns out the dom traversal was a bit wonky on my first attempt. This fixes it!

Attempt number 2 at fixing svgs

---

lib/Guideline/index.js
tests/Guideline/Guideline.js

Seems like a sensible callback to add!
Very handy for things like tracking etc.

Add a callback for onToggle in Guidelines

---

tailwind.config.js

Their container clashes with our container, lets ditch theirs

remove container from tailwind

---

lib/Notification/inline/NotificationInlineBase.js
lib/Notification/inline/inlineTypes.js
stories/components/Notification.js

When mobbing the new notifications on the app we decided we wanted the ability to turn off box shadows on InlineNotifications for certain circumstances. This PR lets us do just that

add prop to control shadow on NotificationInline

---

lib/Dropdown/DropdownAction.js
lib/Dropdown/README.md

Very small pr, just as the title says

Add a value prop to dropdown action

---

lib/ButtonNew/ButtonBase.js
lib/ButtonNew/ButtonIcon.js
lib/ButtonNew/ButtonPrimary/ButtonPrimary.js
lib/ButtonNew/ButtonPrimary/ButtonPrimaryDanger.js
lib/ButtonNew/ButtonTertiary/ButtonTertiary.js
lib/ButtonNew/ButtonTertiary/ButtonTertiaryDanger.js
tailwind.config.js

A few last minute sneakers to get the buttons styled as they should look!
- Updates the `ButtonBase` margin and padding values - they were a bit off from the designs
- Adds outlines to all buttons on focus
> Branched from https://github.com/gathercontent/gather-ui/pull/704
Check it 👉https://share.getcloudapp.com/jkulQbqj
https://www.figma.com/file/66iSurBAx32DWrJymo9NKL/GCDS-%E2%80%93-Web-UI?node-id=77%3A0

Update/Buttons Styling Snags

---

lib/Comment/Comment.js
lib/Comment/CommentBody.js
lib/Conversation/stories/ConversationWithReply.js
lib/Conversation/stories/mockData.js

Really quick & simple peaks tweak here. If _YOU_ are the person being mentioned, it should be purple. If it's anyone else it's still bold but not purple. Simples!
There's also a sneaky padding change because it looked a bit off.

Purple highlighting for if you're mentioned in a comment

---

lib/Comment/CommentBody.js
lib/Comment/EditCommentForm.js
lib/Conversation/Conversation.js
lib/Conversation/stories/CollapsedConversationWrappedBoundary.js
package-lock.json
package.json

Just some little fixes in here, They are as follows:
- Boundary click watcher boundaries were a bit dodgy. I have moved the margin up a level to exclude the boundary.
- `split of undefined` error. This was because we don't refresh the comments body when it's created. I had to do a bit of useEffect fanciness to fix this.
- CMD + Enter didn't submit the edit form. This was because focus was going a bit funky. I fixed how it sets whether it's being focussed in react-mentions.

Conversation refactor mob feedback

---

lib/Conversation/Conversation.js

Background colour should be white. Previously you could see other comments behind it when opening because our DOM isn't fast enough.

Conversation background colour

---

lib/Comment/EditCommentForm.js
lib/Comment/NewCommentForm.js

A couple of bugs appeared in the new conversatons
- CMD + Enter isn't submitting a new conversation
- Mentions were wrapped in []

Fixing a couple of issues with new conversations

---

lib/Tabs/TabsItem.js

Fixing proptype for children of Tabsitem

---

lib/ButtonNew/ButtonTertiary/ButtonTertiary.js
lib/Icon/styles.scss
tailwind.config.js

Master merge for the following PR https://github.com/gathercontent/gather-ui/pull/743
Classic error of forgetting to change the base 🤦‍♂️

Updates ButtonTertiary styles

---

lib/Field/FieldActions.js
lib/Field/FieldContent.js
lib/Field/FieldInstructions.js
lib/Field/FieldLabel.js
lib/Field/FieldMeta.js
lib/Field/FieldNew.js
lib/Field/FieldValidations.js
lib/Field/stories/FieldStory.js
lib/Field/styles.scss
lib/index.js

This is the ground work for adding the new Fields
I found it quite straightfowrad to remove <Col> and <Row> and replace with tailwind grid css, see what you think?

New Fields component (FieldNew)

---

lib/UserSearchDropdown/index.js

Adds title to UserSearchDropdown trigger icon
Related to https://github.com/gathercontent/app/pull/2898

Adds title to UserSearchDropdown trigger icon

---

assets/icons/new-comment.svg
lib/ButtonNew/ButtonIcon/ButtonIconBubble.js
lib/ButtonNew/stories/ButtonIcon/ButtonIconBubble.js
lib/Field/index.js
lib/Icon/index.js
lib/index.js
stories/components/Icons.js
stories/index.js
tailwind.config.js

A new fun button type! This time its ButtonIconBubble.
I've also added the group class to the old field component (its already there in the new one) so I could do some fancy tailwind hover stuff. 
https://www.figma.com/file/66iSurBAx32DWrJymo9NKL/GCDS-%E2%80%93-Web-UI?node-id=77%3A0
lib/ButtonNew/ButtonIcon/ButtonIconBubble.js

Icon button bubble

---

lib/Toolbar/Toolbar.js

Remove the shadow class from the toolbar

---

lib/Layout/Body.js
lib/Layout/InlineSidebar.js
lib/Layout/Section.js
lib/Layout/index.js
stories/components/Layout.js

There are two biggie changes in this PR:
There is now a `InlineSidebar`, which is a sidebar that is not positioned absolute on top of the page, instead it is a part of the flow!
To help with this, there's another addition `Section`. This is just a layout component to group other layout components together. In this case, we have grouped the `SubHeader`, `Body` and `Footer` together in a `Section`, so the sidebar can be next to them!
`stories/components/Layout.js` - You'll find examples of these new components in the story!

Creating InlineSidebar and Section in Layout

---

lib/Toolbar/Toolbar.js

reduce toolbar height

---

tailwind.config.js

We had this option for maxWidth, but not for min or regular width (which i needed!)

Add '30' width config

---

lib/Dropdown/DropdownTrigger.js
tailwind.config.js

Two tiny things in this PR, just going to merge is straight in:
- added `group-hover` variant to `border` in tailwind.
- passing the event into the `DropdownTrigger` onclick.

Some small styling tweaks for the tabs refactor

---

package.json

As `tailwind.config.js` is now transpiled, we need to add `tailwindcss-plugins/gradient` as a peer dep.

Adds tailwind gradient package as a peer dep

---

lib/Field/styles.scss

Having them be different font sizes is weird, so now they're the same

Unify p and li tag font sizes in fields

---

lib/TabsNew/Tab.js
lib/TabsNew/TabAside.js
lib/TabsNew/TabName.js
lib/TabsNew/TabNameForm.js
lib/TabsNew/TabOptions.js
lib/TabsNew/TabsActionGroup.js
lib/TabsNew/TabsGroup.js
lib/TabsNew/TabsRow.js
lib/TabsNew/index.js

Adding some readable classes to tabs

---

lib/BoundaryClickWatcher/index.js
lib/Dropdown/index.js
lib/TabsNew/Tab.js
lib/TabsNew/TabAside.js
lib/TabsNew/TabNameForm.js
lib/TabsNew/TabOptions.js

I should be able to tab through tabs 😏

Improve tabbing for Tabs

---

lib/ConversationContext/index.js

Comment history now uses the new refactored conversation components

Refactoring conversation context to use new new conversations

---

lib/ConversationContext/index.js
stories/components/ConversationContext.js

Hotfix conversation context

---

lib/Field/styles.scss

They don't need a top/bottom margin

fix spacing for nested lists

---

lib/ButtonNew/ButtonIcon/ButtonIcon.js
lib/ButtonNew/common.js
lib/Icon/index.js
lib/OptionMenu/MenuItem.js

Three changes relating to adding the formatting end to end tests https://github.com/gathercontent/app/pull/3056/files
- Passes `iconTitle` prop to `<ButtonIcon />` and `<OptionMenu.MenuItem />`
- Updates `<Icon />` to update the SVG title if the prop changes

Update/Formatting End to End Test Changes

---

lib/Comment/CommentText.js
lib/Conversation/stories/ExistingCommentExample.js

When a comment is edited we want to highlight that for users. This PR adds a `hasBeenEdited` prop for `Comment.Text` components 👍

add edited test to comment text component

---

lib/Comment/CommentDeleteConfirmation.js
lib/Comment/CommentForm.js

Two new props here to aid with tracking. `onMention` to the comment form, and `onCancel` to the `CommentDeleteConfirmation`.

Extra conversation utility props

---

lib/Comment/CommentSubscribeToggle.js
lib/TabsNew/TabAside.js
lib/TabsNew/TabsRow.js

Cleaning up some prop-types to reduce the console noise in tabs + conversations.

Fixing console errors in tabs and conversations

---

lib/index.js

I forgot to export the new `Counter` component

Exporting the counter component

---

lib/Comment/CommentForm.js

We never changed the content of the error message when submitting a comment. This PR does that!

Changing comment error message

---

lib/Field/FieldContent.js

Only active fields should have shadows

---

lib/Field/styles.scss
lib/Figure/FigurePreview.js
lib/Figure/styles.scss

Add min height for new fields

---

lib/ColField/ColFieldLabel.js
lib/EditableChoiceInput/index.js
lib/EditableTextWrapper/index.js

When editing the label on ColField the text would change size, there was also some weird fixed height set which I've overridden and allowed us to pass class names over to the input.
`lib/ColField/ColFieldLabel.js`

ColFieldLabel tweaks

---

lib/index.js

Actually exports useDeferredList

---

lib/ColField/ColField.js
lib/ColField/stories/ColFieldStory.js

Just copying this https://github.com/gathercontent/gather-ui/pull/848

Add the visible prop to ColField

---

lib/ColField/ColField.js

This was on the FieldNew component and I wasn't sure why it was needed, then I came across revisions!
These are used to tell us how a repeatable field has changed

add statuses to ColField

---

lib/Comment/CommentMeta.js

Comment meta doesn't just take a string!

update prop types

---

lib/Guideline/index.js

Just as the title says, pretty small one!

Make guidelines RTL friendly

---

lib/ColField/styles.scss

Field placeholder should be the same size as a fields text

---

lib/EditableTextWrapper/index.js

Another tiddler, pretty self explanatory!

Add a max length for EditableTextWrapper inputs

---

lib/ColField/ColField.js
lib/ColField/ColFieldLabel.js
lib/EditableTextWrapper/index.js

Nothing huge, just a few minor tweaks

A few styling tweaks for ColField

---

lib/ColField/styles.scss
package-lock.json
package.json

Just as the title says, just some styling

tweak padding for ql-editor within ColFields

---

lib/Layout/Footer.js
lib/Layout/Header.js
lib/Layout/InlineSidebar.js
lib/Layout/Main.js
lib/Layout/Section.js
lib/Layout/SubHeader.js
lib/Layout/index.js

Needed to pass some style tags to one of them, so thought I'd sort it for the rest of them too.

Spread rest props on Layout components

---

lib/Modal/ModalHeaderNavigation.js
lib/Modal/index.js
stories/components/Modals.js

A new component for our modals so we can have tabs in the header! Looking a little bit like this: https://share.getcloudapp.com/llu2j19J
Prettier had fun with the story file. I'll comment where the actual new story is.

Modal Header with navigation

---

lib/Modal/ModalHeader.js
lib/SelectionModal/SelectionModal.js
lib/SelectionModal/SelectionModalBody.js
lib/SelectionModal/SelectionModalCategory.js
lib/SelectionModal/SelectionModalColumn.js
lib/SelectionModal/SelectionModalColumnHeader.js
lib/SelectionModal/SelectionModalColumnLoader.js
lib/SelectionModal/common.js
lib/SelectionModal/styles.scss
lib/index.js
stories/components/Modals.js
styles/components/_ui.scss

We have some designs for a new modal type (see figma), which I've decided to call a SelectionModal. We now have a new SelectionModal component that can be used with and in place of other Modal components, I think the new story gives a pretty clear idea on how it works.
https://www.figma.com/file/HWmdpuNLjhxlKUhzYQJWPW/Components?node-id=248%3A783
`stories/components/Modals.js`

Add SelectionModal component

---

lib/ButtonNew/ButtonBase.js
lib/ButtonNew/stories/ButtonPrimary/ButtonPrimary.js
lib/ButtonNew/stories/ButtonPrimary/ButtonPrimaryDanger.js
lib/ButtonNew/stories/ButtonSecondary/ButtonSecondary.js
lib/ButtonNew/stories/ButtonTertiary/ButtonTertiary.js
lib/ButtonNew/stories/ButtonTertiary/ButtonTertiaryDanger.js

Adding a new state just like the title says, peaks approved!

Add a disabled loading state to new buttons

---

lib/ColField/ColFieldInstructions.js

Oops, this got missed out when making new fields

Make linebreaks visible on field instructions (again)

---

lib/InputConfirmationModal/InputConfirmationModal.js
lib/SelectionModal/styles.scss

Nothing big here, should all be self explanatory!

Minor styling changes for new modals

---

styles/bootstrap/_variable-overrides.scss

Update tooltip background colour

---

lib/ColField/styles.scss
tailwind.config.js

A little peaks tweak here, we're changing the h3 size so you can better differentiate between h2s and h3s.

Update field h3 size

---

lib/ButtonNew/ButtonBase.js
lib/ButtonNew/ButtonIcon/ButtonIconDark.js
lib/ButtonNew/ButtonIcon/styles/buttonIcon.scss
lib/ButtonNew/ButtonIcon/styles/buttonIconDark.scss
lib/ButtonNew/stories/ButtonIcon/ButtonIconStory.js
lib/ButtonNew/stories/ButtonStoryItem.js
lib/index.js
tailwind.config.js

Add an option for darker backgrounds to ButtonIcons

---

stories/index.js

Remove useDeferedList story

---

lib/ItemRow/index.js
lib/ItemRow/stories/ItemRowStory.js
lib/ItemRow/styles.scss
lib/Pill/PillBase.js
lib/Pill/PillDefault.js
styles/tools/_mixins.scss

This adds a couple of things:
- A list style for ItemRow
- A new mixin to handle gradient overflows
- xs Pill tweaks

Add list styling for item row

---

lib/ButtonNew/ButtonAvatar/ButtonAvatar.js
lib/ButtonNew/ButtonAvatar/buttonAvatar.scss
lib/ButtonNew/ButtonIcon/ButtonIcon.js
lib/ButtonNew/stories/ButtonAvatar/ButtonAvatarStory.js
lib/ButtonNew/styles/styles.scss
lib/index.js
stories/index.js

You may have noticed we've dropped the caret on the user dropdown in the app. Now that's gone we need a new way to show that our friendly avatar is clickable, so here's ButtonAvatar.

Add a new ButtonAvatar component

---

README.md

Remove travis from readme

---

lib/ButtonNew/styles/styles.scss

fix casing

---

lib/FinderNavigation/styles.scss

tiny padding tweaks

---

lib/ColField/ColField.js
lib/ColField/stories/ColFieldStory.js
lib/ColField/styles.scss

We can now say a ColField is selected and it will give it a lovely 2px blue border
http://g.recordit.co/DDLoVC4pCO.gif

Add selected state to ColField

---

lib/SelectionBar/index.js
lib/index.js
lib/src/components/animated/AnimatedWrapper.js
lib/src/components/animated/AnimatedWrapperStory.js
stories/index.js

~~A bit like our `LayoutSubheader` (pretty much a copy paste from there!)~~ we sometimes need to shrink our selection bar depending on what's doing on with the layout. 
Update: No longer just a copy and paste! We now have a `AnimatedWrapper` component which this utilises!

Add animate options to selection bar

---

lib/index.js
lib/src/components/selectionControls/SelectionControlsStory.js
lib/src/components/selectionControls/radio/RadioInput.js
lib/src/components/selectionControls/radio/radio.scss
lib/src/components/selectionControls/selectionControls.scss

Just like the previous checkbox pr, but in radio button form, oooh.

Add a lovely radio input component

---

lib/src/modules/inventoryItem/InventoryItemStory.js

The build falls over when running `yarn storybook` currently, this fixes it

fix error by importing the new cjs dnd backend

---

lib/ColField/ColFieldLabel.js
lib/ColField/styles.scss
lib/src/components/componentWrapper/ComponentWrapperHeader/ComponentLabel.js
lib/src/components/componentWrapper/componentWrapper.scss
lib/src/modules/renameInput/renameInput.scss

Now that we have a fancy new component (https://github.com/gathercontent/gather-ui/pull/920) we should use it

add new RenameInput component to ColField and ComponentWrapper

---

lib/src/components/componentWrapper/ComponentWrapperBody.js
lib/src/components/componentWrapper/ComponentWrapperFooter.js
lib/src/components/componentWrapper/ComponentWrapperStory.js
lib/src/components/componentWrapper/componentWrapper.scss

Pretty much as it says on the tin - to be used when we hover structure fields over a component structure field body.
Action 🎥  https://share.getcloudapp.com/Jru1j6PX

Adds hovered property to ComponentWrapperBody and ComponenWrapperFooter

---

lib/src/modules/navigationItems/NavigationItem.js
lib/src/modules/navigationItems/NavigationItems.js
lib/src/modules/navigationItems/NavigationItemsStory.js
lib/src/modules/navigationItems/NavigationProvider.js
lib/src/modules/navigationItems/navigationItems.scss
stories/index.js
styles/components/_ui.scss

Welcome to my first module!!
This PR adds a new module to represent Navigation Tabs.
I have consulted some accessibility guidelines on web navigation when doing this to make sure we're all good. I'll paste some links below regarding that. There's some fancy aria & role stuff in here that seems important!
Styling-wise it's fairly bare bones, it serves my purpose in the uploader but will not do other things I imagine we would need from them (e.g. editable tab names). Those extra changes are for a conversation in the future. My opinion would be that this is strictly for navigation and nothing else though!
https://www.w3.org/WAI/tutorials/menus/structure/
https://www.w3.org/TR/wai-aria-practices/examples/menubar/menubar-1/menubar-1.html# …

Creating the navigation module

---

lib/src/components/dropzone/Dropzone.js
lib/src/components/dropzone/DropzoneStory.js
package.json
stories/index.js
yarn.lock

This here PR has a new Dropzone component. It uses the newest version of `react-dropzone` (hooks, fancy!). And has mostly stolen the styling from the equivalent component in app. 
https://www.figma.com/file/66iSurBAx32DWrJymo9NKL/GCDS-%E2%80%93-Web-UI?node-id=492%3A5275
`lib/src/components/dropzone/Dropzone.js`

Creating a Dropzone component

---

lib/src/components/modal/Modal.js
lib/src/components/modal/ModalBody.js
lib/src/components/modal/ModalFooter.js
lib/src/components/modal/ModalHeader.js
lib/src/components/modal/ModalStory.js
lib/src/components/modal/modal.scss
lib/src/modules/navigationItems/navigationItems.scss
package.json
stories/index.js
styles/components/_ui.scss
yarn.lock

This is the beginning of our modal components. At the moment they're very basic compound components. Most of the new code is the usage of a new modal library (`react-modal`). 
This PR focuses on ensuring the new modal looks/acts like our existing modals, so we shouldn't see any difference!
There is more to do around modals still, but this felt like a good time to get what I had into a PR.
Still to do:
- Flesh out the compound components
- Look at the props of the old modal and ensure we have that functionality built into the new ones.
https://www.figma.com/file/66iSurBAx32DWrJymo9NKL/GCDS-%E2%80%93-Web-UI?node-id=6266%3A829
https://share.getcloudapp.com/geu4xwwO
`lib/src/components/modal/Modal.js` - Creation of the new modal
`lib/src/components/modal/modal.scss` - Styling the new modal

Modal Components

---

lib/src/components/componentWrapper/ComponentWrapperFooter.js

Adds className prop to ComponentWrapperFooter

---

assets/icons/plusIcon16.svg
lib/Icon/index.js

Switch out plus icon to the new one

---

lib/src/components/modal/Modal.js
lib/src/components/modal/modal.scss

I have wanted to make the new Modal component has compatible with existing work that I could, so I have scoured app and found the most popular props we use and ensure they're usable in the new one. There ended up not being too many, with size being the most important one.
I also had a bit of a hassle with the theme colors and RGB mixins, so had to revert back to hardcoding (but with a comment so it should appear if we ever do a ctrl+f for the theme.
`lib/src/components/modal/Modal.js`

Fixing modal styling and adding new props

---

lib/src/modules/searchInput/SearchInput.js
lib/src/modules/searchInput/SearchInputStory.js
stories/index.js

Nothing new here, it's all taken from the existing one so should be able to replace it in app soon!

Creating a search input module

---

lib/src/components/viewOptions/ViewOptions.js
lib/src/components/viewOptions/ViewOptionsStory.js
lib/src/components/viewOptions/viewOptions.scss
stories/index.js
styles/components/_ui.scss

A new component! ⚠️
This is the nice subheader that you'd see on a files & media/project library tab. It has a search input, a sorting dropdown, and a view switcher. There's also an option to add extra actions!
I had gone back and forth as to whether this should be split into more compound components, but I ended up feeling like it was too much of an over-abstraction. There aren't too many components here and it feels manageable.
https://www.figma.com/file/66iSurBAx32DWrJymo9NKL/GCDS-%E2%80%93-Web-UI?node-id=6266%3A832
https://share.getcloudapp.com/jkueoBb4
`lib/src/components/viewOptions/ViewOptions.js`

ViewOptions Component

---

lib/src/components/modal/Modal.js
lib/src/components/modal/ModalFooterConfirm.js
lib/src/components/modal/ModalStory.js
lib/src/components/modal/modal.scss

A component for the ModalFooterConfirm modal! It's just a nice footer with some buttons and some text.
https://www.figma.com/file/66iSurBAx32DWrJymo9NKL/GCDS-%E2%80%93-Web-UI?node-id=6266%3A832
https://share.getcloudapp.com/NQuJzXBb

Creating a ModalFooterConfirm component

---

lib/src/components/modal/Modal.js
lib/src/components/modal/ModalHeaderTabs.js
lib/src/components/modal/ModalStory.js
lib/src/components/modal/modal.scss
lib/src/modules/navigationItems/navigationItems.scss

Here we create a new component to represent tabs in a modal header!
https://share.getcloudapp.com/v1uNR8yb
https://www.figma.com/file/66iSurBAx32DWrJymo9NKL/GCDS-%E2%80%93-Web-UI?node-id=6266%3A832
Top to bottom

Modal Header Tabs Component

---

lib/Dropdown/DropdownContent.js
lib/Dropdown/styles.scss
lib/DropdownMenu/styles.scss

This can cause an issue with nested dropdowns, so sometimes we want to ditch it

Add an option for the dropdown animation not to end in a transform

---

lib/ButtonNew/ButtonSecondary/ButtonSecondaryDanger.js
lib/ButtonNew/stories/ButtonSecondary/ButtonSecondaryDangerStory.js
lib/index.js
stories/index.js

Just as the title says, nothing crazy here

A new ButtonSecondaryDanger button type!

---

lib/src/components/modal/Modal.js
lib/src/components/modal/ModalFooterConfirm.js
lib/src/components/modal/ModalHeader.js
lib/src/components/modal/ModalStory.js
lib/src/components/modal/modal.scss

The new modal class names clash with the old ones, giving some funky results in the app!

Fixing new modal class names

---

lib/src/components/modal/modal.scss
lib/src/prefabs/modalUpload/ModalUploadBody.js

I introduced a couple of hefty style issues with my last hotfix, this hotfix fixes those fixes.

Various style fixes for ModalUpload

---

lib/src/components/componentWrapper/ComponentWrapper.js
lib/src/components/componentWrapper/ComponentWrapperHeader/ComponentWrapperHeader.js
lib/src/components/componentWrapper/ComponentWrapperStory.js
lib/src/components/componentWrapper/componentWrapper.scss

Just mirroring how this looks and works on fields

Add component counter for repeatables

---

lib/DnD/Draggable.js

Just as the title says! Just like our canDropChecker, but the drag flavour

add canDragChecker to Draggable

---

lib/src/components/componentWrapper/ComponentWrapper.js
lib/src/components/componentWrapper/ComponentWrapperBody.js
lib/src/components/componentWrapper/ComponentWrapperFooter.js
lib/src/components/componentWrapper/ComponentWrapperHeader/ComponentWrapperHeader.js
lib/src/components/componentWrapper/ComponentWrapperStory.js
lib/src/components/componentWrapper/componentWrapper.scss

The title says it all really. We need to show the status of components in a revision so this adds those styles.
Prettier also formatted that `scss` file!
Top to bottom

Adding revision status to components

---

lib/TopBar/index.js
lib/TopBar/styles.scss
stories/components/TopBar.js

Add light grey topbar style

---

lib/ColField/ColFieldLabel.js
lib/src/components/componentWrapper/ComponentWrapperHeader/ComponentLabel.js
lib/src/components/componentWrapper/ComponentWrapperHeader/ComponentWrapperHeader.js
lib/src/modules/renameInput/RenameInput.js
lib/src/modules/renameInput/RenameInputForm.js

Add max length to RenameInput 

---

lib/src/components/componentWrapper/ComponentWrapperBody.js
lib/src/components/componentWrapper/ComponentWrapperFooter.js
lib/src/components/componentWrapper/ComponentWrapperHeader/ComponentWrapperHeader.js

pass classnames to ComponentWrapperBody and ComponentWrapperHeader

---

lib/ColField/styles.scss

Blockquote should be the same font size as p

---

lib/src/modules/inventoryItem/InventoryItemStory.js
lib/src/modules/inventoryItem/inventoryitem.scss

We didn't have these until now!

Add disabled styles for InventoryItems

---

lib/ButtonNew/ButtonSecondary/ButtonSecondary.js
lib/ButtonNew/ButtonSecondary/styles/buttonSecondary.scss
lib/ButtonNew/styles/buttonBase.scss
lib/ButtonNew/styles/styles.scss

Export ButtonSecondary styles to its own class

---

lib/index.js
lib/src/components/dropdownContent/DropdownContentFooter.js
lib/src/modules/calendar/Calendar.js
lib/src/modules/calendar/calendar.scss
lib/src/modules/dateSet/DateSetTimeDropdown.js
lib/src/prefabs/dueDateDropdown/DueDateDropdown.js
lib/src/prefabs/dueDateDropdown/DueDateDropdownStory.js
stories/index.js
tailwind.config.js

A prefab for a `DueDateDropdown`! We have a case of the dreaded dropdown within a dropdown!! 
This may need some extra props adding, but this should give you the basics and a good start point to go off from.
http://g.recordit.co/m1fvO1OTv4.gif
`lib/src/prefabs/dueDateDropdown/DueDateDropdown.js`

Add a DueDateDropdown prefab

---

lib/index.js
lib/src/components/dropdownContent/DropdownContent.js
lib/src/prefabs/assigneeDropdown/AssigneeDropdown.js
lib/src/prefabs/assigneeDropdown/AssigneeDropdownStory.js
stories/index.js

Another prefab! Same as the `DueDateDropdown` prefab where there's probably some props missing, but this should give a decent starting point. 
http://g.recordit.co/ihGMPcVmqQ.gif
`lib/src/prefabs/assigneeDropdown/AssigneeDropdown.js`

Add an AssigneeDropdown prefab

---

lib/index.js
lib/src/components/workflowStep/workflowStep.js
lib/src/components/workflowStep/workflowStep.scss
lib/src/components/workflowStep/workflowStepActions.js
lib/src/components/workflowStep/workflowStepMeta.js
lib/src/components/workflowStep/workflowStepProvider.js
lib/src/components/workflowStep/workflowStepTitle.js
lib/src/prefabs/assigneeDropdown/AssigneeDropdown.js
lib/src/prefabs/dueDateDropdown/DueDateDropdown.js
lib/src/prefabs/workflowDropdown/WorkflowDropdown.js
lib/src/prefabs/workflowDropdown/WorkflowDropdownContent.js
lib/src/prefabs/workflowDropdown/WorkflowDropdownStory.js
lib/src/prefabs/workflowDropdown/workflowDropdown.scss
stories/index.js
styles/components/_ui.scss

This PR creates a prefab for the Workflow Dropdown. It also creates a whole story that puts together all of the smaller components we've been making. 
STILL TO FIX:
- The positions of the dropdowns are way off, I can't quite figure out why.
https://p-76FWwk4.t1.n0.cdn.getcloudapp.com/items/Apuz6gYe/7862cbd3-67ac-40db-9459-4887eeab9a53.gif?v=98257605fe7d3a4182981812280a5bd3
`lib/src/prefabs/workflowDropdown/WorkflowDropdownStory.js`

Workflow Dropdown Prefab

---

lib/src/prefabs/assigneeDropdown/AssigneeDropdown.js
lib/src/prefabs/dueDateDropdown/DueDateDropdown.js

Fixing the titles of the new workflow dropdowns

---

lib/src/modules/dateSet/DateSetTimeDropdown.js

Adding a title to the time dropdown

---

lib/Dropdown/DropdownContent.js
lib/src/components/workflowStep/workflowStepCollapsibleBody.js
lib/src/prefabs/workflowDropdown/WorkflowDropdownContent.js
lib/src/prefabs/workflowDropdown/workflowDropdown.scss

I'll comment on the code changes because there's multiple fixes in here!

Fixing various workflow dropdown snags

---

lib/src/components/workflowStep/workflowStep.js
lib/src/components/workflowStep/workflowStepTitle.js
lib/src/modules/input/input.scss
lib/src/modules/statusIndicatorCircle/statusIndicatorCircle.js
lib/src/modules/statusIndicatorCircle/statusIndicatorCircle.scss
lib/src/prefabs/dueDateDropdown/DueDateDropdown.js
lib/src/prefabs/workflowDropdown/WorkflowDropdownContent.js

There's a few here so I'll explain them in the comments.

Various fixes to workflow dropdown G-UI Components

---

lib/src/components/workflowStep/workflowStep.js
lib/src/components/workflowStep/workflowStepTitle.js

Fixing dodgy classnames logic

---

lib/Pill/PillGreenPrimary.js
lib/Pill/PillGreenWhiteText.js
lib/Pill/common.js
lib/Pill/index.js
lib/src/components/workflowStep/workflowStep.scss
lib/src/components/workflowStep/workflowStepTitle.js
lib/src/modules/statusIndicatorCircle/statusIndicatorCircle.js
lib/src/modules/statusIndicatorCircle/statusIndicatorCircle.scss
lib/src/prefabs/dueDateDropdown/DueDateDropdown.js

I had to add a new Pill for green because there are now two different ones depending on where it is in the app! I've also fixed a couple of dodgy styling issues.

Adding new pill colour and fixing some workflow styling

---

lib/src/modules/person/Person.js
lib/src/modules/person/PersonStory.js
lib/src/modules/person/person.scss

We would like to highlight (bold) a part of the person's name to show which part of the string matches the search value!
Peaks has also decided to unbold the person's name, meaning the highlighted part is bold! And prettier had fun with the sass file.
https://share.getcloudapp.com/YEuZPBdv

Adding highlight property to the Person component

---

lib/src/modules/person/Person.js
lib/src/modules/person/PersonStory.js
lib/src/modules/person/person.scss
lib/src/prefabs/assigneeDropdown/AssigneeDropdown.js

Just a couple of small tweaks from implementing assignees into the workflow.

Various fixes to assignee components

---

lib/src/modules/person/Person.js

ANOTHER hotfix, we are cutting off the end of the persons name

---

lib/Avatar/AvatarGroup/index.js
lib/src/components/workflowStep/workflowStep.js
lib/src/components/workflowStep/workflowStepActions.js
lib/src/modules/person/Person.js
lib/src/prefabs/assigneeDropdown/AssigneeDropdown.js
lib/src/prefabs/dueDateDropdown/DueDateDropdown.js

I have used comments to explain the changes here. There's a few different ones!

Various tweaks to the workflow assignment

---

lib/helpers/useSize.js
lib/src/components/workflowStep/workflowStep.scss
lib/src/components/workflowStep/workflowStepCollapsibleBody.js
lib/src/components/workflowStep/workflowStepMeta.js
lib/src/prefabs/workflowDropdown/workflowDropdown.scss
package.json
yarn.lock

A user reported an issue when using the new workflow dropdown on a smaller resolution. Peaks ended up giving some feedback on how we can improve the responsiveness, here are those changes!
This PR is mostly style updates. As well as a change to our collapsible logic to handle the changing of sizes better.
https://trello.com/c/T6gWuxPx/1588-regular-the-new-workflow-ui-makes-it-difficult-to-leave-longer-notes

Various fixes to the responsiveness of workflow dropdown

---

lib/src/modules/calendar/calendar.scss
lib/src/prefabs/assigneeDropdown/AssigneeDropdown.js
lib/src/prefabs/dueDateDropdown/DueDateDropdown.js

Various fixes to assignees and due date drop downs

---

lib/src/components/personSearch/PersonSearch.js

We need the max height or the dropdown goes on forever!

Setting a max height for the person search dropdown content

---

lib/src/components/personSearch/PersonSearch.js

Whoops, forgot to add an overflow

---

lib/helpers/TextHighlighter.js
lib/src/modules/input/InputWithMentions.js
lib/src/modules/person/Person.js
lib/src/modules/person/person.scss
lib/src/prefabs/workflowDropdown/workflowDropdown.scss

Just a few little extra bits of polish here to make it all slick.
- Fixed an issue where an invisible element caused overflow
- Fixed an issue when the mentions dropdown caused overflow issues
- Added in highlighting to the subtitle of a `Person` component. And created a new component for that lovely highlighting!
- The `Person` component is now aligned to the center.

Workflow Dropdown styling

---

lib/src/prefabs/dueDateDropdown/DueDateDropdown.js

A nice to have, it really improves the look and feels! Just another use of `useLoader` here pretty much.

Adding loading state to DueDateDropdown

---

lib/src/modules/input/InputWithMentions.js
lib/src/modules/input/input.scss
lib/src/prefabs/workflowDropdown/workflowDropdown.scss

Adding portal prop to inputWithMentions to make it fixed position

---

lib/UserSearch/index.js
tests/UserSearch/index.spec.js

Refactor unsafe lifecycle methods from UserSearch

---

lib/ExpandingTextArea/index.js
stories/components/ExpandingTextArea.js
tests/ExpandingTextArea/ExpandingTextArea.js

Remove unsafe lifecycle methods from ExpandingTextArea

---

lib/src/components/personSearch/PersonSearch.js
lib/src/prefabs/workflowDropdown/workflowDropdown.scss

BOGOF in this PR:
- Some styling to help the workflow dropdown be center.
- Filtering in the `PersonSearch` component now works for emails!
https://share.getcloudapp.com/Apuzq7o7

Workflow centering & Email filtering in PersonSearch

---

stories/components/Modals.js

Just as the title says, nice and easy one

Remove bootstrap form component usages and replace with our own

---

lib/DueDatePicker/DueDateTime.js

Remove the remaining instance of bootstrap dropdown

---

lib/ConfirmationModal/index.js

Title says it all. `ConfirmationModal` is very structured!

Adding prop for extra buttons in a ConfirmationModal

---

styles/helpers/_borders.scss

Re-adding a class I accidentally deleted

---

lib/Avatar/AvatarGroup/index.js
lib/Avatar/AvatarGroup/styles.scss
lib/Avatar/AvatarWithPopover.js
lib/Avatar/stories/AvatarStory.js

A stepping stone to ditching Popover from GUI

Remove PopoverWrapper from Avatar components

---

lib/Progress/Unit/index.js

Replace bootstrap tooltip in ProgressUnit

---

lib/TooltipWrapper/index.js

Pass onclick to tooltip wrapper

---

lib/index.js
lib/src/modules/optionMenuItem/OptionMenuItem.js
lib/src/modules/optionMenuItem/OptionMenuItemStory.js
lib/src/modules/optionMenuItem/option-menu-item.scss
stories/index.js
styles/components/_ui.scss

A small little component to use in selection dropdowns

Add a new OptionMenuItem module

---

lib/ButtonNew/ButtonPrimary/ButtonPrimary.js
lib/ButtonNew/ButtonPrimary/styles/buttonPrimary.scss
lib/ButtonNew/ButtonSecondary/styles/buttonSecondary.scss
lib/ButtonNew/styles/styles.scss

A bit of bonus text overflow styling in SecondaryButton too

Move ButtonPrimary styles from inline to a nice class

---

lib/src/prefabs/workflowDropdown/workflowDropdown.scss

Changing overflow on the workflow dropdown to handle safari bugs

---

lib/Modal/styles.scss
lib/src/components/modal/modal.scss

Modals and extend beyond the viewport height. This PR resolves that as well as removing a fixed height from the modal header.

Slight modal styling changes

---

lib/ButtonNew/ButtonIcon/ButtonIconContainedDanger.js
lib/ButtonNew/ButtonIcon/ButtonIconDanger.js
lib/ButtonNew/ButtonIcon/styles/buttonIcon.scss
lib/ButtonNew/ButtonIcon/styles/buttonIconContainedDanger.scss
lib/ButtonNew/ButtonIcon/styles/buttonIconDanger.scss
lib/ButtonNew/stories/ButtonIcon/ButtonIconStory.js
lib/index.js

Also exporting out the inline tailwind styles for ButtonIconDanger into a single class

Add ButtonIconContainedDanger

---

lib/Modal/styles.scss

Update max width and height on medaOnly modals.

Fixing max width and height on media only modals

---

lib/src/components/sidebar/SidebarHeader.js

Adding flex shrink 0 to the close icon in a sidebar

---

lib/index.js
lib/src/modules/slider/Slider.js
lib/src/modules/slider/SliderStory.js
lib/src/modules/slider/slider.scss
stories/index.js
styles/components/_ui.scss

Added an input type='range' component styled as per designs.
https://trello.com/c/mVDsODkM/2210-add-zoom-control-to-image-settings-sidebar

add input type='range' slider component

---

lib/src/modules/slider/Slider.js
lib/src/modules/slider/SliderStory.js
lib/src/modules/slider/slider.scss

Slider focus has been updated so the thumb is highlighted when the input is focused. 
Track is now highlighted in blue up to the selected value. Firefox has a really handy pseudo element you can use to do this, but Chrome requires some extra CSS.

slider improvements

---

lib/src/modules/grid/Col.js
lib/src/modules/grid/Grid.js
lib/src/modules/grid/GridStory.js
lib/src/modules/grid/Row.js
lib/src/modules/grid/grid.scss
stories/index.js

Goodbye floats, goodbye minus margins, goodbye clearfixes... hello flex!
Mainly styling changes here, its a bit hard to parse so you might be better off grabbing this branch locally and looking at the file in your ide/checking out the new grid story

make grid/row/col use flex

---

lib/TooltipWrapper/styles.scss
lib/TooltipWrapper/tippystyles.scss

Copy tippy styles to our own file

---

lib/src/modules/controls/Control.js

A small thing that peaks asked for a little while, thought i'd add it in while im in the filecard area!

add a danger option to controls

---

.gitignore
.postcssrc.json
package-lock.json
package.json
postcss.config.js
styles/prod.scss
tailwind.config.js

All warnings now fixed, use `npm run compile:css` to take it for a spin!

use parcel to compile our scss into a single css file

---

lib/src/modules/Button/stories/ButtonIcon/ButtonIcon.stories.js
lib/src/modules/Button/stories/ButtonPrimary/ButtonPrimary.stories.js
lib/src/modules/Button/stories/ButtonPrimary/ButtonPrimaryDanger.stories.js
lib/src/modules/Button/stories/ButtonSecondary/ButtonSecondary.stories.js
lib/src/modules/Button/stories/ButtonSecondary/ButtonSecondaryDanger.stories.js
lib/src/modules/Button/stories/ButtonSuccess/ButtonSuccess.stories.js
lib/src/modules/Button/stories/ButtonTertiary/ButtonTertiary.stories.js
lib/src/modules/Button/stories/ButtonTertiary/ButtonTertiaryDanger.stories.js

This size is only used for ButtonIcon, so that should be the only story that displays it

Clean up lg button size

---

lib/PageInformation/styles.scss

minor tweak to stop a naughty scrollbar

fix page information overflow

---

lib/DueDatePicker/index.js

Updates the function used to set time to correctly set the time.
https://trello.com/c/BQMSGNPc/2724-regular-unable-to-set-a-due-date-time-in-bulk-actions

update handleTimeClick function to correctly set time

---

package-lock.json
package.json

fix build error by updating @babel/plugin-proposal-class-properties

---

lib/Modal/styles.scss

Use `128px` in full screen modal width calculation.

update full screen modal width calculation

---

lib/StatusIndicator/styles.scss

Reduces font-weight to 400 on bulk action dropdown.

reduce font weight in bulk action dropdown

---

lib/Navigation/index.js

Just an added guard to make sure the child exists before trying to access it

fix error when navigation has conditional children

---

.github/workflows/npm-publish.yml
README.md

shout if you think we should add anything else to the README

fix publish npm action and update readme with project status

---

.github/workflows/npm-publish.yml

I removed this after pasting from mono, but it looks like we do need it

hopefully this fixes it

---

.github/workflows/npm-publish.yml

action needs to use node 12 (sadly)

---

.github/workflows/npm-publish.yml

try turning off auto tagging in place of our manual step

---

package.json

bump version and add tag since action failed again

---

lib/src/modules/person/Person.js
lib/src/modules/person/Person.stories.js

Adds a little locked icon to a person

add locked person prop

---

lib/Avatar/index.js
lib/src/modules/person/Person.js

turn off active state style inheritence for locked status icons

---

lib/SearchDropdown/SearchResults.js

fix linting error

---

.postcssrc.json
.storybook/main.js
package-lock.json
package.json

Fibers causing chaos with node 16

remove fibers and update sass-loader, remove autoprefixing from postcss

---

lib/Avatar/index.js
lib/Avatar/stories/Avatar.stories.js
lib/Avatar/styles.scss

Now we can match some newer ui a bit better

add remove functionality ui to Avatar

---

lib/Avatar/AvatarGroup/styles.scss
lib/Avatar/index.js
lib/Avatar/stories/Avatar.stories.js
lib/Avatar/styles.scss
lib/TooltipWrapper/index.js
lib/src/modules/person/Person.stories.js

1. position the lock properly
2. remove pointer for locked avatars 
3. fix person story
4. change tooltip default position

avatar snags 2.0

---

lib/SelectionProvider/index.js
lib/SelectionProvider/stories/Selection.stories.js
lib/SelectionProvider/useObjectSelector.js
lib/SelectionProvider/useShiftSelect.js

Now we can also pass up some additional data when selecting items. The idea is we can pass up some additional data in an object, and then that will be keyed against the id you've also passed up.

add selected data to selection provider

---

.github/workflows/chromatic.yml
package-lock.json
package.json

add chromatic

---

lib/src/modules/Button/ButtonTertiary/styles/buttonTertiary.scss

Updating tertiary button hover style to match designs.

update tertiary button hover style

---

lib/Button/styles.scss

Update button hover states on billing pages as raised on our trello FE board - https://trello.com/c/CxrOzh7M/268-update-button-hover-states-on-billing-pages

Overwriting bootstrap styles on hover

---

lib/TabsNew/TabNameForm.js
lib/TabsNew/TabsRow.js

JIT mode getting confused with variable based classnames

fix issues with tabs

---

lib/SelectionProvider/index.js

We needed a way to update the additional data in our selection provider, this allows us to do so!

update selection provider with data update function

---

lib/src/modules/Button/ButtonIcon/styles/buttonIconBase.scss

Updates button icon hover/active styling to match new designs.

GC-212 update button icon hover/focus styling

---

lib/FinderNavigation/FinderGroup.js
lib/FinderNavigation/styles.scss
stories/components/FinderNavigation.stories.js

add a meta prop to FinderGroup

---

lib/Dropdown/DropdownInfo.js
lib/Dropdown/index.js
lib/src/prefabs/dueDateDropdown/DueDateDropdown.js

Passing workflowDueDate; Adding DropdownInfo component + adding due date info. Also removed the title from this dropdown as no longer required (as discussed with Design).
There was a requirement to allow for addition info in the dropdown. 
I adjusted the prefabs DueDateDropdown to accommodate the workflowDueDate and output the string accordingly.

Adding DropdownInfo component

---

assets/icons/project-root.svg
lib/Icon/index.js
stories/components/Icons.stories.js

Add project root icon

---

.github/workflows/chromatic.yml

Makes sense to have this here too

comment the chromatic link on prs

---

lib/DueDatePicker/DueDateLabel.js

Replaces `Due to be completed by` with `Due in` on the due date label component.

GC-506 update DueDateLabel text

---

lib/src/prefabs/assigneeDropdown/AssigneeDropdown.js
lib/src/prefabs/dueDateDropdown/DueDateDropdown.js

Add the `autoPositionLeft` prop to the assignee and due date dropdown to ensure they align to the trigger.

GC-519 ensure assignee and due date dropdowns are aligned correctly

---

lib/Icon/styles.scss
lib/src/components/form/FormSubmitButton.js

Added the `defaultActiveColor={false}` prop to the form submit button so that the white colour is not overridden.

GC-508 add prop to form submit button icon

---

lib/Dropdown/DropdownInfo.js
lib/src/prefabs/dueDateDropdown/DueDateDropdown.stories.js

- Added rounded corners to the DropdownInfo component
- Added a story for DueDateDropdown with additional info (e.g. dynamic due date set by workflow)

GC-520 rounded corner issue at the top of the due date picker

---

lib/DueDatePicker/index.js
lib/src/modules/calendar/Calendar.js
lib/src/modules/calendar/Calendar.stories.js
lib/src/modules/calendar/calendar.scss
stories/components/duedates/DueDatePicker.stories.js

Part of https://bynder.atlassian.net/browse/GC-518

GC-518 - Create parity between old and new due date pickers

---

lib/src/prefabs/dueDateDropdown/DueDateDropdown.js
lib/src/prefabs/dueDateDropdown/DueDateDropdown.stories.js

Match helper to the design
* [-] blue icon. different icon (seems to be fixed already)
* [-] vertically centred (seems to be fixed already)
https://www.figma.com/file/qczzkf9AiM6pDAIAZkl7zp/Due-date-update?node-id=59%3A9996&t=cAf45SV9PnFJYf5a-0

GC-496 Match helper to the design

---

lib/src/prefabs/dueDateDropdown/DueDateDropdown.js

Changing text colour to improve colour contrast

GC-496 -  making text correct colour accessible

---

lib/src/prefabs/dueDateDropdown/DueDateDropdown.js

GC-560 don't display the dynamic message if its a fixed due date

---

lib/src/modules/calendar/calendar.scss

🥫 - Adding styles to match the mono calendar.

GC-567 - Making cal look like mono buttons

---

lib/src/prefabs/dueDateDropdown/DueDateDropdown.js

Just using a helper lib that we use elsewhere in GUI

GC-573 Issue/pluralisation dynamic interval

---

lib/src/prefabs/dueDateDropdown/DueDateDropdown.js

We needed a way to add a non-removable default due date & time to handle fixed workflow due dates.

GC-639 add default date and time props to duedate dropdown

---

lib/DueDatePicker/DueDateLabel.js
lib/Form/RadioButton/Input.js

We still have some remaining “console clutter” in our FE repos that should be resolved or at least documented for future resolution.
Some issues will be in the remix-gc and webapp repos, and others may be from our ui libraries (gather-ui, mono) and more from our npm packages (such as tippy, intercom et al)
https://bynder.atlassian.net/browse/GC-669
* gather-ui: https://github.com/Bynder/gathercontent-gather-ui/pull/1194
* webapp: https://github.com/Bynder/gathercontent-app/pull/5102

GC-669 Snags - console error and warnings

---

lib/src/prefabs/dueDateDropdown/DueDateDropdown.js

We have one for dynamic dates, we need one for fixed dates too

GC-651 add fixed due date copy to due date dropdown

---

lib/src/components/form/FormSubmitButton.js

Adds a prop to the form submit button called `hideSuccessState` that when true hides the success state of the button.

add prop to hide button success state

---

lib/Button/index.js

Button had no no way of passing a keyUp event

passing keyup to button

---

lib/Dropdown/DropdownAction.js

I need a keyDown event listener on this dropdown action. Followed similar style to the onClick event

Adding keyDown to Dropdown action

---

package.json

make sure we declare our node version

---

lib/Dropdown/.types/DropdownTypes.ts
lib/Dropdown/DropdownAction.tsx
lib/Dropdown/DropdownActionGroup.tsx
lib/Dropdown/DropdownContent.tsx
lib/Dropdown/DropdownFooter.tsx
lib/Dropdown/DropdownHeader.tsx
lib/Dropdown/DropdownInfo.tsx
lib/Dropdown/DropdownProvider.tsx
lib/Dropdown/DropdownSection.tsx
lib/Dropdown/DropdownTrigger.tsx
lib/Dropdown/index.tsx
stories/components/Dropdown.stories.tsx

All of the Dropdown compound component is now fully typescript, no expect errors or anys to be seen 👍

GC-1171 Feature/typescript dropdowns

---

lib/CollectionsTable/styles.scss

Incorrect max width on [this PR](https://github.com/Bynder/gathercontent-gather-ui/pull/1227)

GC-1351 - Incorrect max width

---

lib/CollectionsTable/styles.scss

https://share.getcloudapp.com/qGu6Ol8r

GC-1369 - Item names appear to be truncated too soon

---

lib/src/modules/revisionList/stories/RevisionsList.stories.tsx

accessibility linting error which only shows up when trying to publish :/

for some reason this is stopping a build

---

lib/Avatar/AvatarGroup/index.tsx
lib/src/modules/revisionList/RevisionListItem.tsx
lib/src/modules/revisionList/RevisionListStatus.tsx
lib/src/modules/revisionList/revisionList.scss
lib/src/modules/revisionList/stories/RevisionsList.stories.tsx

Changing some styling and adding some missing tooltips

GC-1487 Feature/revision list tweaks

---

stories/components/Dropdown.stories.tsx

Adds an example to the Dropdown component stories to show how to use a dropdown within a dropdown to enable the AI prompt sub-menu to be built.

GC-1479 add example of dropdown within dropdown

---

lib/src/modules/revisionList/revisionList.scss

GC-1530 fix borders for RevisionList

---

.babelrc

generate sourcemaps on build

---

lib/BlankSlate/index.tsx
lib/ColField/stories/ColField.stories.tsx
lib/Comment/CommentActions.tsx
lib/Dropdown/.types/DropdownTypes.ts
lib/DueDatePicker/DueDateButton.tsx
lib/DueDatePicker/DueDateTime.tsx
lib/DueDatePicker/index.tsx
lib/FigurePlaceholder/FigurePlaceholder.tsx
lib/Icon/index.tsx
lib/LoadingOverlay/index.tsx
lib/Logo/index.tsx
lib/OptionMenu/stories/OptionMenu.stories.tsx
lib/SectionHeader/SectionHeaderTitle.tsx
lib/TabsNew/TabOptions.tsx
lib/UserSearchDropdown/index.tsx
lib/src/components/componentWrapper/ComponentWrapper.stories.tsx
lib/src/components/personSearch/PersonSearch.tsx
lib/src/modules/preview/PreviewImage.tsx
lib/src/modules/revisionList/stories/RevisionsList.stories.tsx
lib/src/prefabs/files/fileCard/FileCard.stories.tsx
package.json
tests/BlankSlate/index.tsx
tests/LoadingOverlay/LoadingOverlay.spec.tsx
tsconfig.json

generate types when building dist

---

package-lock.json
package.json

GC-2102 remove pre commit hooks

---

lib/ConfirmationModal/index.tsx
lib/src/components/form/Form.stories.tsx
lib/src/components/form/Form.tsx
lib/src/components/workflowStep/WorkflowStep.stories.tsx
lib/src/modules/selectionControls/SelectionControls.stories.tsx
lib/src/prefabs/workflowDropdown/WorkflowDropdown.stories.tsx

Add correct props type to the `Form` component to allow some `ts-expect-error` comments to be removed from the AI Generate prompt components in webapp.

add correct props type to Form

---

package.json

fix linting

---

lib/CheckToggle/styles.scss

There was no way to tab to the toggle switch (at least visually). I've matched mono the styles from mono.

Adding focus and hover states to toggle.

---

lib/src/modules/Button/ButtonTertiary/styles/buttonTertiary.scss

[tertiary buttons now have a subtle border](https://www.notion.so/gathercontent/Buttons-5c08ad30cc704893930d71260c634fbb?pvs=4#1698fa80af7f4ffdb30f6012d32cc290)

update button tertiary border

---

tailwind.config.js

change the default border radius from 6 to 8

---

lib/Navigation/styles.scss

Removing no outline styles on focus form menuItems

Removing the no outline from menu items

---

lib/Resizable/styles.scss

:bug: Resize gutter should only appear blue on hover

---

lib/Resizable/index.tsx
stories/components/Resizable.stories.tsx

Expose an event from the resizer so that we can add tracking events in CSR for both when a user resizes an element and what size too.

✨ GC-2848 - Expose onResizeComplete event for resizable elements

---

lib/Notification/blip/NotificationBlip.tsx
lib/Notification/blip/styles/NotificationBlip.scss
stories/components/Icons.stories.tsx
stories/components/NotificationBlip.stories.tsx
styles/components/_ui.scss

- Added the notification blip, taken from Mono made some minor tweaks to get it to play nice with the GUI `IconButton`
- Added a notification blip story
- Added the notification icon to the icon story

GC-3155 Notification Blip

---

lib/src/components/personSearch/PersonSearch.stories.tsx
lib/src/components/personSearch/PersonSearch.tsx
lib/src/modules/input/Input.tsx

- Fix broken PersonSearch story
- Increase size of PersonSearch input

GC-3418 Contributor text input visual regression

---

package-lock.json

`npm audit fix` to resolve the vulnerability.

📦 GC-3079 - Critical vulnerability around @babel/traverse

---

lib/Logo/index.tsx

missed a class

---

lib/src/components/modal/modal.scss
lib/src/prefabs/modalUpload/ModalUpload.tsx

Update the `ModalUpload` to use the newer Modal component for it's container so it has the correct width.

GC-3644 make ModalUpload the correct width

---

lib/src/modules/preview/PreviewImage.tsx

GC-3644 gui-invisible should just be invisible

---

lib/BlankSlate/styles.scss
lib/FinderNavigation/styles.scss
lib/Logo/index.tsx
lib/Modal/styles.scss
lib/TabsNew/Tab.tsx

Largely caused by mono having reset styles, and this not having one

fix mono style clashes

---

package-lock.json
package.json

As part of [GC-3777 - Align FE repos to all use the same TS version (5.3.3 latest)](https://bynder.atlassian.net/browse/GC-3777)

⬆️ Upgrade gather-ui to TypeScript V5 

---

lib/Avatar/AvatarInformation.tsx
lib/Avatar/styles.scss
lib/src/modules/input/Input.stories.tsx
lib/src/modules/input/InputWithMentions.tsx

We need the “pending” UI adding to the component in storybook, dynamically rendered based on whether a user is pending or not. Attributed will be assigned to the `user` object and should be a boolean.
- Design: [Pending users](https://www.figma.com/file/XYIYoxEkUAJqF6bH6bCrR7/Pending-users?type=design&node-id=1-29854&mode=design&t=9IJjzUI2g4ApcIxx-0)
- JIRA: [GC-3805](https://bynder.atlassian.net/browse/GC-3805)
[GC-3805]: https://bynder.atlassian.net/browse/GC-3805?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

💄GC-3805   Apply pending UI to participant dropdown (in CSR > item editor)

---

lib/src/components/personSearch/PersonSearch.tsx
lib/src/modules/person/Person.tsx
lib/src/modules/person/person.scss
lib/src/prefabs/assigneeDropdown/AssigneeDropdown.stories.tsx

We need the “pending” UI adding to the component in storybook, dynamically rendered based on whether a user is pending or not. Attributed will be assigned to the `user` object and should be a boolean.
Similar to https://github.com/Bynder/gathercontent-gather-ui/pull/1329, but on a seperate component
- Design: [Pending users](https://www.figma.com/file/XYIYoxEkUAJqF6bH6bCrR7/Pending-users?type=design&node-id=1-29854&mode=design&t=9IJjzUI2g4ApcIxx-0)
- JIRA: [GC-3802](https://bynder.atlassian.net/browse/GC-3802)
[GC-3802]: https://bynder.atlassian.net/browse/GC-3802?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

💄 GC-3802   Add pending state to the nameplate UI component

---

lib/Comment/CommentText.tsx
lib/Conversation/stories/mockData.ts

Adds the tooltip to users who have pending invites, also adds the dashed bottom border to the tag
Please keep an eye out for the sibling PR that bumps CSR to use these changes 😇 
Design: https://www.figma.com/file/XYIYoxEkUAJqF6bH6bCrR7/Pending-users?type=design&node-id=1-32472&mode=design&t=W6AEjjnQZOgWyhGh-0

:sparkles: Add pending state to comment form and user search

---

lib/src/components/modal/ModalHeader.tsx

TL: DR; don't show the close button if there is no close action
https://bynder.atlassian.net/browse/GC-2905

🩹 GC-2905 "Friendly warning" modal cross does nothing

---

lib/Comment/CommentText.tsx
lib/Conversation/stories/mockData.ts

:adhesive_bandage: GC-3888 Pending user tooltip should be inline not block

---

README.md

GC-2722 update readme with deprecation notice
