- .storybook/webpack.config.js
- assets/icons/loader.svg
- lib/ProgressButton/index.js
- lib/ProgressButton/styles.scss
- lib/index.js
- package.json
- stories/index.js
- styles/main.scss
- tests/ProgressButton.js
Imported AjaxButton as a renamed ProgressButton.
Styling for the loading needs a little bit of tweaking, but leaving this for later.
Also added the inline SVG loader to bring in the loader icon.
There were no tests for this component so for now it's just the bare minimum, needs a hella lot more coverage.
> Feature: progress button

- lib/Button/styles.scss
- lib/Modal/Modal.js
- lib/Modal/ModalColumn.js
- lib/Modal/ModalContent.js
- lib/Modal/ModalFooter.js
- lib/Modal/ModalHeader.js
- lib/Modal/index.js
- lib/Modal/styles.scss
- package.json
- stories/index.js
- styles/main.scss
- tests/Modal/Modal.js
Add an example for a simple Modal.
I had to create two small components for this, Header and Footer, since our only implementation of the React Modal component so far in the app hides them... and we didn't really account for them when we first built it.
This is one of those to really be refactored!
> Add Modals

- .babelrc
- package.json
There was a bug that was causing one of our components to break the whole library. This was due to how inline SVG's were handled in the `ProgressButton` component.
Adding this plugin resolves the issue.
> Fixes to Babel setup

- lib/Carousel/Slides.js
- lib/Carousel/index.js
- lib/Carousel/styles.scss
- lib/index.js
- stories/components/Carousel.js
- stories/styleguide/ExampleCarouselChild.js
- styles/settings/_colours.scss
I have resolved how we expose the navigation methods to those consuming the component via cloning the children prop and adding props to them.
This mean that if you need to access navigation methods then you'll need to pass a component down as a child, which I believe is nicer anyways.
If you don't need to access the navigation then just add divs etc as children 👍 
------
I've added an Issue on a bug around how the component calculates the active indicator when the user goes passed the last slide.
> Refactor Carousel

- lib/Field/index.js
- lib/FileCard/index.js
- lib/Form/Checkbox/Input.js
- lib/Form/RadioButton/Input.js
- stories/components/FileCard.js
This turns effectively the Choices/Radio components into controlled components, rather than uncontrolled ones (which we'll need to revisit, sooner rather than later). But the priority is to make them work with the Item editor first, and then in isolation.
This also fixes the actions object being passed down to the FileCard.
> Fix form choices

- lib/Avatar/index.js
- lib/Avatar/styles.scss
- stories/components/Avatar.js
This adds a few changes as discussed for the Avatar component, although not all of them are done.
- Black and white picture given an `offline` property (previously, `fadedOut`)
- Fall back to initials if the `url` property is Falsy
- Remove background if the image is shown (as not to show a leaking background colour)
> Add black and white offline property for Avatar. Minor styling tweaks

- .travis.yml
- README.md
- package.json
Adds Travis CI to the project.
It also changes the way we load FontAwesome dependency - I'm not sure why it was loaded like this?
Note - I tried setting up on CodeShip but then changed my mind and have now removed that, it is just using Travis CI. But some of the builds are marked as "failed" - this is just because I didn't get Codeship passing before I removed it. I think this will go away the next commit/PR we make.
> Feature travis ci

- lib/Field/FieldActions.js
- lib/Field/FieldAside.js
- lib/Field/FieldValidations.js
- lib/Field/index.js
- lib/Field/styles.scss
- lib/index.js
- stories/components/Field.js
A `Field` component can use a aside component within it. A field aside can hold anything but it's main purpose is to hold a single button/action.
An example for an action would be something like adding a comment/annotation to the entire field or depending on the consumer maybe something more specific.
> Add FieldAside

- lib/Field/FieldAside.js
- tests/Field/Field.js
- tests/Field/FieldAside.js
The PR https://github.com/gathercontent/gather-ui/pull/86 was missing the spreading of props to the inner wrapping div.
This is very import for setting inline styles for instances where you may need to align the aside with an element within the child component. E.g. when hovering over a paragraph align the aside to the height of the node.
This PR also adds the missing test for the `FieldAside` 👍
> Spread props to div wrapper

- stories/components/Field.js
There was a clash of transforms with the field aside element. This PR resolves that and makes it clear that action expects another element within it.
> Update field component story

- lib/Field/index.js
- tests/Field/Field.js
A small change which fixes instances where the instructions aren't set and set the margin is still applied causing more space to be created.
> Hide instructions when none are set

- styles/generic/_global.scss
- styles/tools/_mixins.scss
It's been required a few times that we should be font smoothing when on certain devices (those with high density screens).
> Font smoothing for retina(ish) screen

- lib/Field/index.js
- lib/Field/styles.scss
- stories/components/Field.js
- tests/Field/Field.js
- tests/SectionHeader/index.js
There is an issue where using `Guideline`s inside of `Field` means that we apply text styles that we don't want. For situations like this we should be able to turn formatting off.
This PR allows that 👍
> Field Formatting Prop

- lib/Conversation/CommentForm/index.js
- lib/ExpandingTextArea/README.md
- lib/ExpandingTextArea/index.js
- package.json
- tests/Conversation/CommentForm/CommentForm.js
- tests/ExpandingTextArea/ExpandingTextArea.js
This PR adds the newly added `ShortcutTrigger` component to the `CommentForm` component. This allows us to trigger the submit for comment via `cmd+enter` or `ctrl+enter`.
> Add keyboard shortcuts for submitting comments

- lib/Avatar/styles.scss
Easy fix for avatars appearing 'oval', this happened most notably in conversations when the conversation container was narrow.
> stopping flex from shrinking avatar--supporting

- lib/BoundaryClickWatcher/index.js
- lib/Conversation/Comment.js
- lib/Conversation/CommentForm/index.js
- lib/Conversation/README.md
- lib/Conversation/index.js
- package.json
- tests/Conversation/Comment.js
- tests/Conversation/CommentForm/CommentForm.js
- tests/Conversation/Conversation.js
This PR adds the handlers for when comments are edited and passes up the id of the comment and the current value.
This is handy when you need to perform an action based on when the value is empty etc...
> Add comment edit handlers

- lib/EditableTextWrapper/styles.scss
- lib/TopBar/styles.scss
Little fix that stops the text prematurely being cut off when editing a title that sits within the top bar
> giving page information's editable text wrapper a bit more room

- lib/Field/index.js
- tests/Field/Field.js
As title says and removing conditional which requires field to have existing instructions for the input to load in
> Use ExpandingTextArea on field instructions instead of a plain input

- lib/BoundaryClickWatcher/index.js
- lib/Guideline/index.js
- lib/LoadingOverlay/index.js
- tests/BoundaryClickWatcher/BoundaryClickWatcher.spec.js
- tests/Guideline/Guideline.js
There are times where the additional `div` applied by `BoundaryClickWatcher` will affect styling. This change allows the developer to add classes to resolve this.
> Add className to BoundaryClickWatcher

- lib/EditableTextWrapper/index.js
Found an issue where EditableTextWrapper sets the value state to props.value a bit too aggressively. This had the effect of setting state.value before props.value had actually changed, as a result resetting state.value back to before any changes had happened. 
I've just moved that setState from stopEditing() into the isEscKey conditional as thats the only place we want that to happen.
> fix EditableTextWrapper bug

- lib/Conversation/styles.scss
Really small PR
Added a bit of CSS to stop long strings popping out of the conversation text area. overflow-wrap and word-wrap are both used as firefox only likes word-wrap, and everything else likes overflow-wrap apparently. lol browsers
> Fixing long strings overflowing outside of conversations

- assets/data.js
- lib/Button/styles.scss
- lib/DropdownMenu/index.js
- lib/DropdownMenu/styles.scss
- stories/components/Button.js
- stories/components/Dropdown.js
- tests/DropdownMenu/index.js
Adding a new 'outline' button style and a few bits to DropdownMenu:
- Changed closeDropdown as it was closing the dropdown regardless of where you clicked, overriding the toggleItems function.
- Adding a new 'withAdditional' item type
- Adding a downIcon prop incase you want to use that icon instead of the caret
- Adding a fullWidth prop to render the dropdown button and items full width
- Adding 'active' item functionality
- Tests now exist for this component
> DropdownMenu additions

- lib/Form/Label/index.js
A few props set to required in Label wont be passed down if its an "other" option, causing some ugly errors.
> Fix prop errors for radio other options

- lib/Conversation/Comment.js
- lib/Conversation/styles.scss
After integrating a preview patch there is a new issue with wrapping for the delete comment confirmation UI.
> Fix button wrapping

- lib/Conversation/Comment.js
- lib/Conversation/CommentList.js
- lib/Conversation/README.md
- lib/Conversation/index.js
- lib/ExpandingTextArea/index.js
- lib/Person/index.js
- stories/components/ExpandingTextArea.js
- tests/Conversation/Comment.js
- tests/Conversation/CommentForm/CommentForm.js
- tests/Conversation/Conversation.js
This PR adds a `onCommentCancel` prop to the `Conversation` component 👍 
Handy if we need to reset or stop some functionality after the user has cancelled a edit and we don't have access to the input value for said comment.
> Add on comment cancel prop

- lib/Conversation/styles.scss
The focus fallback is used so when we cancel comment edits etc we can still be focused in the component.
> Fixed the focus fallback

- lib/Conversation/CommentForm/index.js
This fixes a bug where if you edited a comment without changing the value the comment content would disappear.
This was down to the inputValue state in CommentForm only getting a value if the input value had actually changed.
> Issue: Comment editing content loss bug

- lib/List/styles.scss
Currently when a parent is current in the list component it shades the child components in the same background colour. This PR fixes that 😄
> Amends the styling so the current styling is only applied to 1 item

- .travis.yml
- lib/Conversation/Comment.js
- lib/Conversation/CommentForm/index.js
- lib/Conversation/index.js
- lib/Conversation/styles.scss
- package.json
- tests/Conversation/Comment.js
A few bugs fixed: 
1. The showComment state being lost when clicking on the edit Button (now a div)
2. You couldn't delete all the text in a CommentForm if you pass a value prop
3. The focus fallback would throw you down the page when focused (set back to fixed, if this was changed for a reason give me a shout, couldn't see any nastiness caused)
> fixing a few bugs around comment editing

- lib/Field/index.js
- tests/Field/Field.js
Don't show instruction when none are set for base fields.
> Hide Instructions (when not set)

- lib/BlankSlate/styles.scss
- Reduced size of content
- Included unused `__svg` class in `.scss` file
- Added styles for `__svg` class
> Blank slate fixes

- lib/SearchInput/styles.scss
I've added `outline: none` to the search input, however it looks like buttons already have these applied, so maybe the structure button isn't using the same class as the buttons in gather-ui.
> Removed outline from search input • Added a border on search input focus

- lib/FileCard/styles.scss
The FileCard label would appear over other dom elements (i.e. a fixed position header).
So I've just removed the z-index, this seems to have no negative impact, the label is still visible with or without a preview image, not sure why it was there to begin with. 😅
> FileCard label z-index

- lib/Conversation/CommentForm/styles.scss
When editing comments the textarea doesn't share the same right padding which means the text can move between states causing a poor experience.
> Fix Inline Comment Edit Padding

- lib/ConfirmationOverlay/README.md
- lib/ConfirmationOverlay/index.js
- lib/ConfirmationOverlay/styles.scss
- lib/Conversation/Comment.js
- lib/Conversation/styles.scss
- lib/FileCard/index.js
- lib/FileCard/styles.scss
- lib/index.js
- styles/components/_ui.scss
- tests/ConfirmationOverlay/index.js
- tests/Conversation/Comment.js
Splitting the confirmation overlay (used to live in conversations) into its own component.
We can make this a little more complete in the future once `backdrop-filter` is better supported.
> New ConfirmationOverlay component

- lib/UserList/index.js
- tests/UserList/index.js
it now calls props.handleClearResults if state.showSearch has been changed to false (and only if there were any results at all)
> fix UserList not clearing search results on SearchDropdown hide

- lib/TopBar/styles.scss
Adding a higher z-index will allow dropdowns it contains to sit above others used elsewhere in the app
> Add a higher z-index for the top bar

- lib/Field/styles.scss
Cheeky quick little way of adding linebreaks to field instructions
> Add white-space: pre-line to field__instructions

- lib/Conversation/styles.scss
Tasty chocolate revel
(another whitespace: pre-line)
> Line breaks in comments

- lib/DueDatePicker/DueDateLabel.js
- stories/components/DueDatePicker.js
- tests/DueDatePicker/DueDateLabel.js
This PR fixes the issue where `fromNow` being used in the `dueDateLabel` component causes issues due to the incorrect format being supplied.
To make the component easier to use the moment aspect has been removed. That element can be composed outside the component and inserted as a prop. Win win.
> Due date fix

- lib/Field/styles.scss
- lib/FileCard/styles.scss
Fields have an addition margin right against the content but they also have padding from the grid system. Removing this additional margin means they sit where we expect them to sit.
> remove unnecessary margin-right

- lib/Form/RadioButton/Group.js
- tests/Form/RadioButtonGroup.js
In #314 we altered input groups and we forgot to update the `onTextChangeHandler` method to match the `onChangeHandler`. This fixes that issue.
> Fix radio input group onTextChange bug

- lib/Conversation/Comment.js
- lib/Conversation/README.md
- lib/Conversation/index.js
- lib/Conversation/styles.scss
- stories/components/Conversation.js
- tests/Conversation/Comment.js
As the title says.
Comments can have a `hasFailed` property which will display a little failure message and retry button (which will call our brand new retryComment prop)
> Add a failure state to comments

- lib/Conversation/index.js
- lib/Conversation/styles.scss
- tests/Conversation/Conversation.js
This fixes an issue where using Conversation with BoundaryClickWatcher wont work properly if the reply count is clicked to activate the conversation, directly after clicking the 'cancel' button to deactivate the conversation. 
We don't render the reply count if the conversation is active, so when the boundary watcher checks if event.target is inside the container, it doesn't think it is, because it wasn't or wont be rendered. Hiding it with some css instead achieves the same result, but without this weird bug!
> Fix clicking conversation reply count with boundary click watcher

- package.json
- yarn.lock
`react-bootstrap` is breaking CI. For more information: https://github.com/react-bootstrap/react-bootstrap/issues/3231
> Fix react bootstrap version

- lib/Search/styles.scss
Added a white left drop shadow to gracefully hide nav items when the expanded search bar covers nav items.
> Search box drop shadow

- lib/Dropdown/styles.scss
We used transform to vertically position right aligned dropdowns which caused a clash with our new animations that also uses it. Should be back to normal now
> Fix right aligned dropdowns

- lib/Search/SearchInput.js
- lib/UserSearch/index.js
- tests/Search/SearchInput.spec.js
Small PR. Fixing a bug where if the UserSearch is wrapped in a form, hitting enter when the input is in focus will submit the form.
> Stop UserSearch submitting form bug

- lib/List/ListItem.js
- tests/List/ListItem.spec.js
A simple PR that stops un-mounting sub lists so we retain the open hierarchy until the users refreshes the page of course 😄
> stop un-mounting sub lists

- lib/FormModal/README.md
- lib/FormModal/index.js
- stories/components/Modals.js
Ok, I didn't realise we had the onHide prop which is usually passed from the parent `withModalTrigger`... seems to be quite hidden, but I guess I'm just not used to it. So if we want to close the form modal by clicking the "cancel" button, we need to pass it the parent - parent - onHide prop! This will in tern, pass the `show` prop down all the layers and set it to `false`. I've also removed the `cancelHandler` prop, I don't think we'll usually need this?
> FormModal should use onHide prop, which is passed from withModalTrigger

- lib/ItemRow/styles.scss
- lib/List/ListItem.js
- lib/List/styles.scss
- tests/List/ListItem.spec.js
Our list component has a regression when we moved to `List` and `ItemRow`. When a title is too long the actions are pushed out of the container.
> Fix overflow issues

- lib/Button/index.js
- lib/Button/styles.scss
- lib/ConfirmationDropdown/README.md
- lib/ConfirmationDropdown/index.js
- lib/ConfirmationDropdown/styles.scss
- lib/Dropdown/index.js
- lib/Dropdown/styles.scss
- stories/components/Dropdown.js
- tests/ConfirmationDropdown/index.spec.js
- tests/Dropdown/Dropdown.spec.js
To make the `ConfirmationDropdown` more re-usable I have changed it quite a bit;
- we now use the `Dropdown` components rather than re-creating logic we already have
- we allow consumers to define their own dropdown trigger (via props.children)
- we handle the promise process itself within the component showing a loader!
> ConfirmationDropdown alterations

- lib/ConfirmationDropdown/README.md
- lib/ConfirmationDropdown/index.js
- stories/components/Dropdown.js
- tests/ConfirmationDropdown/index.spec.js
Whilst using the component I found that at times I unmount the component completely after the promise has resolved. Currently, we try to set the state on the component (to reset it) and when it's unmounted this causes a leak.
Adding an `onHide` prop gives us the ability to trigger the logic which would unmount the component resolving the leak on our side 👍
> onHide for ConfirmationDropdown

- lib/ConfirmationDropdown/ConfirmationDropdownContent.js
- lib/ConfirmationDropdown/README.md
- lib/ConfirmationDropdown/index.js
- lib/Dropdown/index.js
- lib/SelectionBar/index.js
- stories/components/Dropdown.js
- tests/ConfirmationDropdown/ConfirmationDropdownContent.spec.js
- tests/ConfirmationDropdown/index.spec.js
- tests/Dropdown/Dropdown.spec.js
Our recent changes to the confirmation dropdown had some design flaws in them like not using the dropdown context supplied to close the dropdown, instead create new props to do something that context already provided us.
The PR also adds handlers for the confirmation promise so when we resolve or reject the confirmation promise we can execute some additional logic.
> Confirmation dropdown promise handlers 

- lib/Field/styles.scss
We need to have different sizes for our headers and text in the editor than what is in our declared typography settings. 
I have set defaults at the top of the file. I'm wondering if I should use the specific px value rather than the rem values. @kyleharper what are your thoughts on this?
> Declare text sizes here as they differ from our styleguide

- lib/ConfirmationDropdown/ConfirmationDropdownContent.js
- lib/ConfirmationDropdown/README.md
- lib/ConfirmationDropdown/index.js
- lib/ConfirmationDropdown/styles.scss
- lib/Dropdown/DropdownFooter.js
- lib/Dropdown/DropdownHeader.js
- lib/Dropdown/DropdownSection.js
- lib/Dropdown/index.js
- lib/Dropdown/styles.scss
- stories/components/Dropdown.js
- tests/ConfirmationDropdown/ConfirmationDropdownContent.spec.js
- tests/ConfirmationDropdown/index.spec.js
The confirmation dropdown has instances where it contains another dropdown but it didn't allow for manual positions to override issues with `autoPosition` on top of `autoPosition`.
As well as that I thought it'd be worthwhile having a component to render a dropdown header which is a new requirement seeing as we have headings and actions alongside each other.
> Confirmation Dropdown Updates

- lib/FinderNavigation/FinderItem.js
- lib/FinderNavigation/styles.scss
- Adds `noIndentation` prop to `<FinderItem />`
- This prop switches the main classname between 'finder__item' and 'finder__item-no-indentation'
- But when you look at the styles, they both apply the same thing, say WHUT!1!?
Take a look at this snippet: https://github.com/gathercontent/gather-ui/blob/master/lib/FinderNavigation/styles.scss#L184-L201
That bad boy basically means that the more parents with the classname `finder__item` a `<FinderItemContent />` component has, the more indented to the right it is (to signify folder structure)
By adding a prop to change the classname, but keep the same styles, we can stop a folder that is not shown from indenting it's children (used in "Archived Items")
Relates to: https://github.com/gathercontent/app/pull/1585
> Adds noIndentation prop to finder item

- lib/CollectionsTable/styles.scss
Some scss changes to fix the above ^ 
If the EditableTextWrapper contained a long bit of text the edit button would be pushed out of sight, also the input would be tiny compared to the cell width.
> Fix issues with EditableTextWrappers in CollectionTables

- lib/DueDatePicker/index.js
Whilst paring with @jamesdarracott we changed the time default for the due date picker component so this starts at 17:00 rather than 00:00. 
Makes sense for deadlines 👍
> Set default for due date picker to 5pm instead of midnight

- lib/Button/styles.scss
- lib/Dropdown/DropdownTrigger.js
- lib/Dropdown/README.md
- lib/Dropdown/index.js
- lib/Dropdown/styles.scss
- stories/components/Dropdown.js
- tests/Dropdown/DropdownTrigger.spec.js
We added the latest `Dropdown` components to be able to compose dropdowns at will in many forms. However, at times we still want to achieve the same look that is provided by `DropdownMenu`, especially the trigger.
This PR adds the ability to add a menu modifier to `<Dropdown.Trigger />` .
--------
I've called the prop `useSelect` as it is a pipe dream of mine to utilise native selects a little more in our `Dropdown` components for accessibility and to increase our progressive nature.
> Dropdown.Trigger useSelect prop

- lib/Conversation/CommentForm/styles.scss
- lib/Conversation/styles.scss
Sometimes the bottom bar covers the mentions/actions in conversations - this gives it some more breathing room
> Stop conversation ui from being unaccessible

- lib/Avatar/AvatarInformation.js
- lib/ConfirmationDropdown/ConfirmationDropdownContent.js
- lib/ConfirmationDropdown/README.md
- lib/ConfirmationDropdown/index.js
- tests/ConfirmationDropdown/ConfirmationDropdownContent.spec.js
I needed to call something when I clicked cancel on a ConfirmationDropdown, and I needed to pass a node as an Avatar name
So I've added both in!
> add onCancel to ConfirmationDropdown and avatar proptypes

- lib/Pricing/PricingText.js
- lib/PricingPlan/styles.scss
- lib/index.js
- stories/components/Pricing.js
A very small fix for the `PricingPlan` styles. I've also removed the `PricingText` component because we don't handle internationalisation so our test env blows up.
> Firefox style fix for PricingPlan component

- lib/Button/styles.scss
- lib/ConfirmationDropdown/styles.scss
As the title says, this should stop this:
> fix button backgrounds on safari

- package.json
- yarn.lock
Lets get rid of this security warning https://github.com/gathercontent/gather-ui/network/alert/package.json/bootstrap/open 
I've had a good look locally and I cant see that this has caused any problems, still worth a hammer on preview regardless.
> Update bootstrap to 3.4.1

- .babelrc
- lib/ProgressButton/index.js
- lib/index.js
- package.json
- styles/helpers/_text.scss
- tests/ProgressButton/index.js
Added an autoSpinner prop to ProgressButton so the spinner stops displaying if the clickHandler has resolved.
Because I'm using async await I've had to add in babel-polyfill, if this isnt agreeable I can just use boring old `.then` 
Also I've added some utility classes, let me know what you think, I dont think we should have a utility class for everything or use these everywhere, but some font sizes and possibly colours will save us a load of custom override styles :)
> Progress button updates & utility classes

- lib/Conversation/index.js
`Conversation` needs to provide `CheckToggle` with an id for it to be able to be clickable. It now passes the conversation id into it.
> Subscription toggle inside conversation now uses the conversation id

- lib/CheckToggle/README.md
- lib/CheckToggle/index.js
- lib/Conversation/index.js
The checked prop was only used in the constructor, meaning that when the prop changes the checked state doesn't reflect it.
> CheckToggle will now also look at its props to see whether it is checked

- lib/CheckToggle/styles.scss
It also decreases margin to the label left, however we don't use that anywhere so it doesn't effect anything.
> decreasing space between label and toggle in CheckToggle

- lib/ButtonGroup/ButtonGroup.js
- lib/ButtonGroup/README.md
- lib/ButtonGroup/styles.scss
- lib/Modal/Modal.js
- lib/Modal/styles.scss
- lib/index.js
- stories/components/Modals.js
- styles/components/_ui.scss
This PR adds some additional modifiers to the modal component. The new modifier allows us to present media (images mainly) without the need for the surrounding modal bootstrapping UI.
> Add media only modal modifier

- lib/Modal/ModalHeader.js
- lib/Modal/styles.scss
- lib/images/ImageLoader/README.md
- lib/images/ImageLoader/index.js
- lib/images/ImageLoader/styles.scss
- lib/index.js
- package-lock.json
- package.json
- stories/components/Modals.js
- stories/components/images/ImageLoader.js
- stories/index.js
- styles/components/_ui.scss
- tests/images/ImageLoader.spec.js
This PR adds some fixes to the media only modal styles so we can't exceed the screen when the image loads. We also add a new component for loading images as at times UI can look pretty shifty when a large chunk of the UI hasn't loaded yet.
> Modal updates & a new ImageLoader component

- lib/Field/styles.scss
Having the not allowed cursor just caused confusion, so lets switch to just the default one
> Change icon for disabled fields

- styles/bootstrap/_variable-overrides.scss
Bootstrap is messing with some breadcrumb styling due to a var being named the same. This resolves it.
> Added override

- lib/BlankSlate/styles.scss
Styles the blank slate contents layout in exactly the same way, but makes the container `display: flex` instead of `display: block`
https://github.com/gathercontent/app/pull/1878
> Styles blank slate content using flexbox

- assets/icons/clock.svg
- lib/Button/styles.scss
- stories/components/Button.js
Update clock icon (I don't think we're using this anywhere, @Cyapow added this in February 2018 when he was working on the Workflow Status Dropdown, I think it was since dropped from the designs??)
It will be used on the new content hub to filter overdue items. I've also had to tweak the sass slightly so that an `icon-only` type doesn't override the red background applied from `danger`.
https://projects.invisionapp.com/share/FZSSB9RK4T7#/screens/371764753
Viewing the storybook
> Update clock icon

- lib/FinderNavigation/styles.scss
A button has been added to the folder navigation in the sidebar to add a new folder. It has a tiny difference in styling.
The icon has been styled to be invisible, this is because it is easier than trying to change the indentation logic to handle no icons. 
That's it really.
> Folder sidebar styles changes

- lib/Form/FormInput.js
- lib/Form/README.md
- lib/Form/styles.scss
- tests/Form/FormInput.spec.js
This makes the inputs look all error-y and optionally display an error message depending on props.
`lib/Form/FormInput.js`
coming soon...
> Add error states to FormInputs

- lib/FinderNavigation/styles.scss
After the sidebar upgrade there were a few niggling styling issues leftover, this css helps fix it.
A lot of hover logic has been added for each item.
Padding has been moved to help the item be fully clickable, not just the text.
is-active logic as been added to the icon links to be blue when the item is active.
https://trello.com/c/R8pCj0vz/196-sidebar-styling-quirks
> Adding some hover styles to the sidebar items

- .gitignore
- lib/TooltipWrapper/index.js
- styles/main.scss
- styles/overrides/_bootstrap.scss
Overrides bootstrap styling for tooltips so that words like supercallerfragerlisticexpealidocious break onto a new line if they are longer than the tooltip width.
Adds a default `delayShow` value of 400 to our `<TooltipWrapper />` component.
- `styles/overrides/_bootstrap.scss`
- `lib/TooltipWrapper/index.js`
https://github.com/gathercontent/app/pull/1903
> Update/Tooltips Word Break & Default Delay Show Value

- lib/FinderNavigation/styles.scss
Pretty small one, just reducing the padding and indentation for the finder panel items.
> Reduce finder panel indentation

- lib/EditableTextWrapper/index.js
- tests/EditableTextWrapper/index.js
Modifies `<EditableTextWrapper />` to accept the following props:
- `onStartEditing`
- `onStopEditing`
These are used in the related PR to stop items from being draggable when the name is being edited.
I've made sure the tests pass but not updated them. I think by updating them I would have just furthered testing implementation detail, when I think in reality the tests need re-writing as integration tests. 
[Trello Card](https://trello.com/c/TzVaXHUj/344-ability-to-select-text-on-the-content-hub-item-name-title-by-dragging-my-curser-when-ive-selected-to-edit-it-this-should-be-poss)
https://github.com/gathercontent/app/pull/1910
> Update/Pass onStart/StopEdit Actions to <EditableTextWrapper>

- lib/SearchInput/index.js
- stories/components/SearchInput.js
- tests/SearchInput.js
Allows us to set an initial value to a `SearchInput`, with an `initialValue` prop.
This is useful for when we want to profile the search input based on the url filters.
I spent quite a while trying to workout why the component wasn't working in the storybook, then I realised we have a `SearchInput` component and a `Search\SearchInput` component - do we need 2?! Also, the `SearchInput` const is called `SearchInputField` inside the index.js file, so it's even more confusing for IDEs!!! 
> Add an initialValue prop to SearchInput

- lib/SearchInput/styles.scss
This is a fix to `SearchInput`, when the clear button moves outside of the textbox it is still clickable, and interferes with other buttons next to the input.
_More detail on what the PR does with as much context as possible. All the changes in your PR should be described here._
https://trello.com/c/gPfuTtuk/192-add-overdue-filtering-to-the-content-hub
This is what happens pre-fix: https://cl.ly/4ca598b1bb76
> Search clear button clickable when not visible

- lib/Button/index.js
- stories/components/Button.js
- tests/Button/index.js
Adds the `Button.id` prop as an attribute to `<button>`.
If we allow an id on the button we can reference it from labels and elsewhere, e.g.
```
<label for="button-id">Toggle filter</label>
<button id="button-id">icon</button>
```
> Add id prop to Button component

- lib/SearchInput/index.js
- tests/SearchInput.js
A lot of work has been done around filtering in the app, as a result there has been a need to control the Search Input, either to clear it or update it from the app.
I have removed the local state and exposed it's API. It is now going to be controlled through the props instead.
**This will be a minor version update.**
> Refactor SearchInput to no longer be controlled

- lib/Form/styles.scss
A real baby pr. Padding styles for `.form__input--noborder` were being overridden by the default focus styles
> Fix padding for noBorder FormInputs

- lib/SearchInput/index.js
- stories/components/SearchInput.js
Inputs should have labels! This is adding a label to the search input.
It is visually hidden, meaning that it is still in the DOM for a screen reader to pick up, but is not visible to the user.
> Search input should have a label

- jest.config.js
- lib/DnD/DnDStory.js
- lib/DnD/DndProvider.js
- lib/DnD/DragPreview.js
- lib/DnD/Draggable.js
- lib/DnD/Droppable.js
- lib/DnD/helpers/getItemStyles.js
- lib/DnD/index.js
- lib/DnD/stories/DnDStory.js
- lib/DnD/stories/DndDropNotification.js
- lib/DnD/stories/FolderDndMock.js
- lib/DnD/stories/ItemDndMock.js
- lib/ItemRow/styles.scss
- lib/Notification/index.js
- lib/index.js
- package.json
- stories/index.js
- yarn.lock
This PR adds UI components which enabled us to establish re-usable drag and drop patterns.
In the past, we've added Drag and Drop to our consuming app directly because we believed it was better suited to not include that domain into this library. However, with the new hierarchy view, we cannot build it without drag and drop.
As well as this we had a number of substantial challenges when building our Drag and Drop experience in the app, to my knowledge the biggest challenge was;
- generating a custom drag preview (which altered based on selection context & warnings)
We thought as well as creating the predictable `Draggable` & `Droppable` components I would also resolve the challenge above by adding a `DragPreview` component and showing how we can disable the default preview per drag …
> Add Drag and Drop UI components

- lib/FolderRow/styles.scss
- styles/helpers/_selected.scss
Using box shadow instead of border to ensure the height stays the same.
> Object selected styling

- lib/Field/styles.scss
The field aside needs to swap sides when in RTL mode. 
Here's a GIF showing why: https://cl.ly/e171058e38da
> Field aside for RTL

- lib/ParticipantInfo/styles.scss
Exactly how the title says, the larger bottom margin looked a bit off
> Fix participant info email padding

- lib/Field/styles.scss
A very small PR to fix some styling issues with the field.
We added `display: flex` to `.field .row` recently but it was missing the wrap property. Without it columns don't function as expected.
> Apply flex wrapping to fields

- lib/ParticipantInfo/styles.scss
As the title says, Avatar had this styling block but ParticipantInfo did not
http://g.recordit.co/1eVoSQRmOC.gif
> Make participant email styling match avatars

- lib/Field/styles.scss
`flex-wrap: wrap` does not work in safari! According to stack overflow this line does. I have tested it in chrome, safari + firefox and it looks good!
> Changing flex property to work in all browsers

- lib/FolderRow/FolderRow.js
- stories/webapp/hierarchy/HierarchyFolderRow.js
- stories/webapp/hierarchy/data.js
When we did some refactoring of a `FolderRow` for the hierarchy, we broke the logic around selecting. This fixes it! 
V1 of `uuid` wasn't giving us different uuid's, that's because it goes off timestamp. The internet™ says that v4 is the place to be. I switched it and it did the job!
The backdrop was used to cover the folder row in a big button to select with, but it's not needed now we'vseparateded the component into multiple composite ones.
> Fixing selecting items and folders in hierarchy story

- lib/Field/styles.scss
`flex-flow: row` caused assets to not wrap onto the new line. It turns out we should have been using media queries in app. so I'm removing that line altogether.
> Removing unneeded flex from row

- lib/Field/styles.scss
Turns out we do need to keep `flex-wrap: wrap` for our columns. I had made an assumption that our bootstrap v4 had flexbox, but we were using v3 which doesn't!
To counter that, we need to ensure that all part of the row are using flexbox, even the `before` and `after`!.
> This is the actual fix now

- lib/EditableTextWrapper/index.js
- stories/components/EditableTextWrapper.js
This adds a prop to have some text inside the pencil button.
EDIT:
A label has also been added for the input that `EditableTextWrapper` renders. All inputs should have labels!
**Any** button that is just an icon should also have some text inside, but set to `visually-hidden`. This is so screen readers know what the button does.
> Adding buttonLabel to EditableTextWrapper

- lib/FolderRow/FolderRowInner.js
- lib/FolderRow/styles.scss
- lib/Windowing/InViewListItem.js
- lib/Windowing/stories/WindowingFolderRow.js
- lib/Windowing/stories/WindowingStory.js
- lib/Windowing/styles.scss
- lib/Windowing/tests/WindowingProvider.spec.js
- stories/webapp/hierarchy/ItemRow/HierarchyItemRow.js
Windowing and widths are funky due to the absolute positioning element to windowing. There were a few bugs with how it was currently done but nothing major.
This PR moves some CSS around to get a correct looking UI (check GIF).
https://cl.ly/81b4aab51683
> Fix widths for windowing items and lists

- lib/Windowing/InViewList.js
The nested windowing gets a bit sluggish when there are lots of layers.
We have added some extra conditional logic around certain calculations, this is so it is not doing them when it doesn't have to!
> Improved performance of windowing calculation

- lib/Conversation/Comment.js
- lib/Conversation/index.js
- lib/Conversation/styles.scss
- lib/Person/index.js
- lib/Person/styles.scss
- stories/components/Conversation.js
- tests/Conversation/Comment.js
This is me rejigging some work I've just done to add a conversation subheading. Instead of a subheading for the conversation, we're showing the user type beneath each author if required.
> remove conversation subheading, replace with showing the user type

- lib/Windowing/Windowing.js
- lib/Windowing/WindowingScroller.js
- lib/Windowing/stories/WindowingStory.js
- stories/webapp/hierarchy/HierarchyStory.js
`containerHeight` prop accepted a number, then converted it to pixels. In app we want to set the height to `100%`, so we've had to change the prop to allow a string instead.
> Changing containerHeight to accept any value

- lib/Windowing/Windowing.js
- lib/Windowing/stories/WindowingIdsMock.js
- lib/Windowing/stories/WindowingStory.js
- stories/webapp/hierarchy/HierarchyCollection.js
- stories/webapp/hierarchy/HierarchyFolderRow.js
- stories/webapp/hierarchy/HierarchyStory.js
When using the component we realised that we unnecessarily built in an id array into the localised state for the context...it would consume the all ids prop and then filter it...however when we needed to update the core all ids prop it didn't hydrate down. 
Now, we could have applied a `useEffect` hook and update the local state but we felt like the provider didn't need to concern itself with this part of the logic. Hence the refactor.
> Refactor windowing to use props rather than localised state

- lib/Windowing/Windowing.js
The prop type for `containerHeight` is incorrect. It can accept either a string or number, not just a string!
> Changing prop type for containerHeight to be either a number or string

- lib/TooltipWrapper/index.js
- lib/TooltipWrapper/styles.scss
Sometimes our TooltipWrapper needs to be used for blur/focus events, adding a tabindex will allow us to do so! See related PR for a usecase.
https://github.com/gathercontent/app/pull/2144
> Add a tabindex to TooltipWrapper

- lib/PageInformation/index.js
- tests/PageInformation/index.js
A required inputLabel prop was recently added to EditableTextWrapper, our PageInformation component uses it but doesn't give it its newly required prop.
> Fix proptype errors for PageInformation

- lib/Button/styles.scss
This PR fixes the previous issues with text links being used as button components, and styles accordingly.
N/A
N/A
N/A
N/A
> Fixing previous styles

- lib/DnD/DragPreview.js
- lib/DnD/Draggable.js
- lib/DnD/helpers/getItemStyles.js
I was having issues getting the drag preview to line up with where I was actually dragging, using clientOffset instead seems to fix it perfectly!
http://g.recordit.co/QfuphfQneb.gif
> Use clientOffset instead of currentOffset for drag previews

- lib/FinderPanelLayout/FinderPanelLayoutHeader.js
- lib/FinderPanelLayout/FinderPanelLayoutLeftContent.js
- lib/FinderPanelLayout/FinderPanelLayoutProvider.js
- lib/FinderPanelLayout/index.js
- lib/FinderPanelLayout/styles.scss
- stories/webapp/peoplegroups/PeopleGroups.js
- stories/webapp/peoplegroups/UsersCol/UsersTable.js
FinderPanelLayout now has the ability to have a sticky header, and correctly offsets the right panel content. Its set up in the webapp/peoplegroups story if you want a closer nose.
http://g.recordit.co/xwvP5RntUg.gif
`lib/FinderPanelLayout/index.js`
> Add sticky header functionality to FinderPanelLayout

- lib/ConfirmationModal/index.js
- lib/ExpandingTextArea/README.md
- lib/ProgressButton/index.js
- lib/TopBar/styles.scss
A few changes related to this PR https://github.com/gathercontent/app/pull/2294
- Stops the progress button callback from being called multiple times (when a user goes mental and clicks as quick as they can, previously we'd send of a bucket load of requests)
- Updates top-bar cell styling
- Removes incorrect docs
- Calls `event.preventDefault()` on ConfirmationModal submit
> Update/progress button multiple clicks (and other bits)

- lib/FolderRow/styles.scss
- lib/ItemRow/styles.scss
- styles/helpers/_selected.scss
- styles/tools/_mixins.scss
Preface - Everything in the hierarchy is based on height. The changes in this PR might seem odd, but they were done in a way to not affect the heights of anything!
Now to the actual PR. Borders around rows in the hierarchy used to be as followed: 
`border: 1px solid grey`
Then when we wanted to apply a 2px border for a selected style we would do the following:
`border: 1px solid blue`
`box shadow: 0 0 1px blue`
This was done to preserve the height and prevent the contents from shifting around when border thickness changed.
This option is no longer viable because there'ss a fancy new border type for - `When my parent has been selected, give me a dashed blue border`. This wasn't possible because you couldn't have a dashed box shadow. Thus we're at this solution, which is an absolute pseudo …
> Changing hierarchy row borders

- assets/icons/bold-tick-small.svg
- lib/StatusIndicator/styles.scss
Minor changes to go alongside this PR: https://github.com/gathercontent/app/pull/2334
- Resize bold-tick svg so it has no padding (and is easier to center!).
- Aligns items center in `status-indicator__label-row`
> Resize SVG & Flex Center Status Indicator Label Row

- styles/tools/_mixins.scss
I need to add `pointer-events: none` to the border pseudo element, so it doesn't cover up anything underneath!
> Border pseudo-element pointer events

- lib/FinderNavigation/styles.scss
- styles/helpers/_selected.scss
This fixes a couple of minor styling issues:
- The `parent-selected` style of a hierarchy row is too light.
- Then new folder form in the sidebar had some padding when focussed.
> Hierarchy DND styling fixes

- lib/DnD/DragLine.js
- lib/DnD/styles.scss
- lib/FolderRow/stories/FolderRowStory.js
- lib/FolderRow/styles.scss
- lib/Hierarchy/styles.scss
- lib/ItemRow/stories/ItemRowStory.js
- styles/components/_ui.scss
This implements some new knobs to show what it would look like when you want to drop things on the rows in the hierarchy.
It also creates a new component called `DragLine` which is what you can render to get that nice line beneath or above something to imply you're dropping next to it!
`ItemRow` and `FolderRow` in the storybook, there are new knobs to play with!
> Styling lines for dragging in the hierarchy

- lib/Field/styles.scss
Makes Field text area scroll on the x-axis if overflowing (to fix issue with long nested lists overflowing the text area)
http://g.recordit.co/ffhASrodMO.gif
> Makes Field text area scroll on the x axis if overflowing

- lib/DnD/DragLine.js
When importing a component using the fancy new empty tags it breaks. It must be a Fragment tag.
> Change empty tag to actual Fragment

- lib/DnD/index.js
- lib/index.js
Look, it's my first day back since Christmas. The issue I have been having was that DragLine wasn't being exported from gather-ui. And Webstorm was trying to import it directly from node modules (for some reason).
> Adding the DragLine component to be exported

- lib/Dropdown/DropdownContent.js
- package.json
- yarn.lock
We had a bug reported where the the `<DueDatePicker />` dropdown would position itself off the bottom of the screen. This dropdown had the prop `autoPosition=true`, so it was supposed to position itself on the screen.
[Video, it really did happen!](https://cl.ly/f3e3c0d8165e)
The `<DropdownContent />` component calculates whether its contents overflows the main window, by saying:
>  "My content starts at ***position X***, and has a ***height of Y*** pixels, therefore I know that if ***X + Y > inner window height***, then my content is off the bottom of the screen, and I need to reposition it!".
To get this Y height value, the component calls `getBoundingClientRect()` on its wrapping div element, inside the function `getStyle()`.
In the previous implementation, `getStyle()` was called …
> FiX/Dropdown Auto Position

- lib/FolderRow/styles.scss
- lib/ItemRow/styles.scss
Each row in the hierarchy should have it's margin shared between top and bottom, instead of just all at the bottom. This makes calculating the drop area easily, as the row is now symmetrical!
6px might seem like a random number, but it is to fill out the whole row in the hierarchy.
> Hierarchy row styles

- styles/helpers/_selected.scss
The styling has been changed for the border of a hierarchy row who's parent is selected. It's now solid and lighter!
> Hierarchy row border for selected parents

- lib/DnD/Draggable.js
We need to hook into some dragging events for the new DnD work. This just adds a couple of props to allow callbacks for `beginDrag` and `endDrag`.
`lib/DnD/Draggable.js`
> Adding events to dragging

- lib/FolderRow/styles.scss
The cursor for the hierarchy folder name should be one for text. That's it, that's the PR.
> Hierarchy folder name cursor

- lib/Field/index.js
- styles/helpers/_disabled.scss
- tests/Field/Field.js
Disabling entire fields from an event POV is a bad idea. Mainly due to read-only mode.
> fix disabled state on fields

- lib/Field/styles.scss
The specific field styles relay heavily on `is-disabled`. This update fixes the change from #651
> Clean up fields CSS after disabled fix

- lib/Conversation/Comment.js
- lib/Conversation/styles.scss
`is-disabled` now turns off pointer events, the delete comment button needs to now be `is-visually-disabled`
> Fixing disabled styles for deleting a comment

- lib/DnD/DndProvider.js
- lib/DnD/Droppable.js
- lib/Field/index.js
- lib/PillInput/stories/story.js
- lib/TooltipWrapper/index.js
Some minor changes  to DnD components and TooltipWrapper
DnD:
- Fix error when you don't provide a custom drag preview
- Pass dragged item info to droppable child
TooltipWrapper
- Allow a manual trigger of the tooltip using hide/show props
> Tweaks to DnD and TooltipWrapper

- lib/Windowing/WindowingScroller.js
When we auto autoflow scroll we had 1 too man scrollbars, this fixes that issue but retains the ability to scroll when overflowing on windowing.
> Change scroll to auto for the windowing scroller

- lib/Windowing/WindowingScroller.js
- lib/Windowing/stories/WindowingStory.js
Just a suggestion - this is one way we could solve the problem when a style prop was passed to the Scroller, which would allow us complete control from the client, but a sensible, resilient, default implementation .
> Allow style prop to be passed to Windowing.Scroller but keep existing CSS props too

- lib/TooltipWrapper/index.js
- styles/helpers/_layout.scss
A couple of changes accumulated whilst adding tests for the Upgrade view.
- Adds flex direction CSS helper
- Changes `children` proptype on `TooltipWrapper` to `node`, as it was throwing errors with certain other render types
> Upgrade view tests changes

- lib/Icon/index.js
- lib/Icon/styles.scss
- styles/helpers/_layout.scss
Here are a few changes that were spawned from the adding the Shareable Upgrade Modal:
> https://github.com/gathercontent/app/pull/2650
- Adds `defaultActiveColor` prop to Icon. By default all SVGs with the class `.icon` are set to blue if they have a parent with the class `.is-active`. Setting this new prop to false overrides this behaviour.
- Updates the `h-border-default` helper to accept a `-clear` postfix, meaning it will clear borders.
- Adds `!important` to the "Margin & Padding" SCSS helper values. This was to override some values set in React Bootstrap.
- I wasn't so sure about this, and am happy to be challenged. I know using `!important` is a bit of a smell, as it makes it impossible to over-write. But I think it is ok for helpers to be impossible to overwrite, as they are …
> Update/Shareables Upgrade Modal Changes

- lib/CheckToggle/index.js
- styles/helpers/_layout.scss
Add `justify-content` helper class.
Same idea as `align-items` helper class.
Also removes the old `space-between` helper class. Usage instances have been removed here and in app (as you will see in the required PR 👇)
Required for https://github.com/gathercontent/app/pull/2655
> Update/Add justify-content helper class

- lib/Button/ButtonWithIcon.js
- lib/StatusIndicator/index.js
Icons have been changed recently to always fill their paths to blue when within a container with the 
`is-active` class. This has caused [various issues](https://share.getcloudapp.com/Apurxvn4) where [icons are going](https://share.getcloudapp.com/04uKLyYd) blue [when they shouldn't ](https://share.getcloudapp.com/Z4u51Dx0)(mainly in dropdowns and fields).
After some fixes in the consuming app, we've realised that there are additional fixes required in `gather-ui`. This is what this PR fixes.
----
I believe this recently added default behaviour should be refactored and replaced with a utility-based solution so we can add a class like `h-path-fill-primary`. We can add a helper for each colour too and remove the need to know if something has the `is-active` class etc.
----
I understand this …
> Fix default active icon colour across multiple component

- lib/DnD/Draggable.js
- lib/DnD/Droppable.js
- lib/Dropdown/DropdownTrigger.js
When writing tests we've noticed that our `Draggable` component can cause memory leaks. The underlining source of the issue is still an unknown but there are complications with `onDrop` and `onEndDrag` which cause us to have memory leaks in our tests.
There's a silver lining. The change to `Draggable` makes sense because when we drop A into B we should handle changes in `onDrop` via `Droppable`. This leaves `onEndDrag` to handle all those times we don't drag something into a dropable.
E.g. we should clear the drag preview when we drag `A` into some whitespace. We should also clear the preview when dropping `A` successfully.
---
I've also added a nice little additional for `Dropdown`s where we can expose the showing boolean so we can log it for usage tracking 👍
> Fix memory leaks with Draggables

- lib/CollectionsTable/styles.scss
A browser issue fix for dismiss-able notifications that was still in my local machine and got left behind 😢 
> Sets collection table to flex-shrink: 0

- lib/ProgressButton/index.js
- lib/SelectionProvider/index.js
Couple of changes to GUI that correspond to the tests added for Bulk Share Items https://github.com/gathercontent/app/pull/2747
This new prop is called after the `clickHandler` promise passed to progress button has resolved, and is passed the result of the promise.
Previously I had a call to close the modal _inside_ the promise `clickHandler` that was passed to a progress button.
This threw a `Cannot update state on an unmounted component` error as we unmounted the modal (and the `<ProgressButton/>` inside it), then the `<ProgressButton/>` tried to update it's `showLoader` state.
The new change means we can call `hideModal` after the `<ProgressButton/>` has finished setting state.
This new prop was added so that we can set the initial selected values in tests (in the Bulk Share example, …
> Update/Bulk Share Test Changes

- lib/Tabs/TabsOptions.js
Adds the `defaultActiveColor=false` prop to the `<TabOptions />` component to fix the issue where the icon was blue instead of white.
> Tab Options Icon Colour Fix

- lib/BoundaryClickWatcher/index.js
- lib/Comment/CommentBody.js
- lib/Comment/styles.scss
- lib/Conversation/Conversation.js
- lib/Conversation/stories/CollapsedConversationWrappedBoundary.js
We would like to be able to tab onto our BoundaryClickWatchers, and apply a focus state to it's children if they care.
This adds the correct events to the watcher and passes down the focussed state through render props.
`lib/BoundaryClickWatcher/index.js`
> Adding focus states for the BoundaryClickWatcher

- lib/Guideline/index.js
- lib/Guideline/styles.scss
- tailwind.config.js
Cheeky peaks tweak - as the title says!
> Adds a border and changes background color of guidline fields

- lib/Tabs/TabsItem.js
- lib/Tabs/index.js
At times we may want to use other components as children `Tabs.Item`, so to allow this we have allowed the `children` prop to be a function...this follows the render prop pattern.
It doesn't cause a breaking change so will be released as a patch.
> Add a render prop for Tab.Item

- lib/ButtonNew/ButtonTertiary/ButtonTertiary.js
- lib/Icon/styles.scss
- tailwind.config.js
@p34ks  has committed to all the Button variations we should experience in GCDS.
Part of this commitment changed the `ButtonTertiary` styles, from a blue theme to grey.
This PR adds those changes.
Updated buttons 👉 https://www.figma.com/file/66iSurBAx32DWrJymo9NKL/GCDS-%E2%80%93-Web-UI?node-id=77%3A0
https://share.getcloudapp.com/Z4uLNNLD
> Updates ButtonTertiary styles

- lib/Field/FieldContent.js
- lib/Field/FieldNew.js
- lib/Field/stories/FieldStory.js
- tailwind.config.js
Where previously we just had an `isActive` toggle (which greyed out the background when false) we will now show when fields have been added, deleted or moved.
The FieldNew takes a `state` prop, which is one of
`ACTIVE`
`ADDED`
`DELETED`
`MOVED_UP`
`MOVED_DOWN`
`UNCHANGED`
You can toggle between these in the storybook.
https://www.figma.com/file/Q3f2o4VMBAb0RAbESE1Fat/Revisions?node-id=149%3A1850
> Add states to new fields

- lib/Field/FieldNew.js
- lib/Field/FieldRepeatableControls.js
- lib/Field/stories/FieldStory.js
- lib/Field/styles.scss
- tailwind.config.js
This will add a row above the field label, which contains the buttons to delete and reorder repeatable fields. It should only show when hovering over the field, or when the field is in an active state.
The repeat position determines which button should show, as well as calculating the repeat position label text, e.g. "01", "02", "03"...
https://www.figma.com/file/HNH1EAEtLOVJRsydtdrxUq/Repeatable-Fields
> Add the Repeable field controls component

- package.json
PR to stop us running tests on the pre-push hook.
If we are all happy for this to go, then we'll kill it. If not, give this a downvote and we can keep it 👍 
> Removes yarn test from pre-push hook

- lib/Field/FieldContent.js
- lib/Field/FieldNew.js
- lib/Field/FieldRepeatButton.js
- lib/Field/FieldRepeatableControls.js
- lib/Field/stories/FieldStory.js
Export the field status consts from FieldNew so these can be accessed from the app:
ACTIVE, ADDED, DELETED, MOVED_UP, MOVED_DOWN, UNCHANGED
And add the button handlers to repeatable field controls/repeat button - didn't actually need these until we tried to port to the app 😄
> FieldNew repeatable updates

- lib/ButtonNew/ButtonLink/ButtonLink.js
Removed specific colours from button link.
Button link doesn't need to care about colours, these can bet set on the app side the same as if it was an anchor tag.
Also makes the background transparent.
> Removes specific colors from ButtonLink

- lib/ProgressButton/index.js
Our progress button spinner was rendering as blue when the button was active, when it should have been white.
This PR fixes this.
I checked every instance of progress button manually, and that probably still wont catch all cases - we need heatmap testing!
> Adds defaultActiveColor={false} to ProgressButton spinner icon

- lib/TooltipWrapper/index.js
We dont always want our tooltip wrappers to be tabbable, for example if you have a dropdown and each dropdown action has a tooltip you have to tab twice in order to get past the tooltip to reach the button.
> Adds a prop to control whether TooltipWrappers are tabbable

- lib/ButtonNew/ButtonIcon/ButtonIcon.js
- lib/ButtonNew/ButtonIcon/ButtonIconDanger.js
- tailwind.config.js
Match GCDS designs for the border radius on small ButtonIcons
The order in the config controls what overrides what, which is why i've rejigged!
> Alter small ButtonIcon border radius

- lib/ButtonNew/ButtonIcon/ButtonIcon.js
- lib/ButtonNew/ButtonIcon/ButtonIconDanger.js
- lib/Icon/styles.scss
- tailwind.config.js
Icon default colours now use the new neutral primary colour, unfortunately I've had to do this the old fashioned way as a sass variable. Once everything is tailwindy we can make this nicer.
Also a new opacity setting and applying that to ButtonIcons
> update icon default colour and ButtonIcon disabled opacity

- lib/BoundaryClickWatcher/README.md
- lib/BoundaryClickWatcher/index.js
- lib/Dropdown/index.js
Reverts gathercontent/gather-ui#711
Reverting these changes as they break our tests.
We test clicking things with `fireEvent.click`, which does not fire the mousedown event, which this PR depends on.
> Revert "Fix/Fix BoundaryClickWatcher to no longer require prop `ignoreClass`"

- lib/OptionMenu/MenuItem.js
Adds white background to the menu item.
Previously it had no background color, and as a result it would intermittently inherit the default browser background color for buttons, which is grey.
> Adds background white to the menu item options

- lib/Field/FieldRepeatableControls.js
- lib/Field/stories/FieldStory.js
When showing fields for revisions, we'll want to omit the repeatable controls entirely. 
Adding some granularity here to allow _some_ controls to be omitted, although not required right now, seems sensible and could be useful in the future (for example when a user does not have permission to delete a field, but could reorder it)
https://share.getcloudapp.com/GGuov2mo
> Allow a user to control whether the different repeatable field controls should be included

- lib/Pill/PillPurple.js
- lib/Pill/common.js
- lib/Pill/index.js
We have a green and red `<Pill>` component, this just adds a purple variation - used for the BETA pill 
https://www.figma.com/file/66iSurBAx32DWrJymo9NKL/GCDS-%E2%80%93-Web-UI?node-id=3450%3A3
> Add the purple pill to gather-ui - used for the BETA pill

- lib/Dropdown/DropdownContent.js
Just a new prop to decide where you want your autopositioned dropdown to appear. It used to default to the right of the trigger, but now we can align it to the left with this prop!
> Adding new autoposition side prop

- lib/TabsNew/TabsScrollShadow.js
> Stop TabsScrollShadow effecting the hit area of the Tabs behind it

- lib/Field/useLoader.js
`setIsLoading()` comes from `useState()` which will trigger a rerender when called. If the component has been unmounted already, this will throw a warning about memory leaks. We only really want to call `setIsLoading()` if the component is still mounted. So we'll `useRef` to a boolean to keep track of whether the component `isMounted`, and use a `useEffect` to update `isMounted` when the component is unmounted.
> Only update state if component is still mounted

- lib/BoundaryClickWatcher/README.md
- lib/BoundaryClickWatcher/index.js
- lib/Dropdown/index.js
Adds the `BoundaryClickWatcher` `ignoreClass` prop fix by reverting a revert.
It was originally reverted as the changes caused tests to fail. These have now been updated to work here https://github.com/gathercontent/app/pull/2931
Origin GUI PR - https://github.com/gathercontent/gather-ui/pull/711
Reverts gathercontent/gather-ui#766
> Revert "Revert "Fix/Fix BoundaryClickWatcher to no longer require prop `ignoreClass`""

- lib/TabsNew/Tab.js
- lib/TabsNew/TabNameForm.js
For tabs, we don't want the form to be focused until the tab is active. We've also improved the usability by adding a label. This PR also fixes inconsistencies with the label / input classes.
> Improve the label to form interactions

- lib/TabsNew/TabAside.js
- lib/TabsNew/TabsActionGroup.js
Two fixes here:
- When the dropdown is active, we need to increase the z-index so they appear over the other tabs.
- The tabs actions should also have more of a right margin to move it further from the scroll bar.
> Extra margin and z-index in tabs

- lib/TabsNew/Tab.js
- lib/TabsNew/TabAside.js
- lib/TabsNew/TabNameForm.js
- lib/TabsNew/TabOptions.js
- lib/TabsNew/TabsActionGroup.js
- stories/components/Tabs.js
This PR fixes a number of issues with tabs;
- when focusing on `TabFormForm` the input width was set incorrectly for the placeholder
- when changing the value in `TabFormForm` the input width was set incorrectly due to the clone not having borders.
- fixes a bug with the story that stopped the `isEditing` context being correctly set when saving the form.
- updates the active prop to the dropdown trigger
- fixes issue where area above and below trigger wasn't clickable
> Alter the calculations for TabNameForm

- lib/TabsNew/index.js
Tabs was already being used as a legit class! So now it's `tabs-new`
> Fix usage of tabs readable class name

- lib/TabsNew/TabNameForm.js
- stories/components/Tabs.js
It wasn't clear how we can use a dropdown action to focus the tab name form so this PR adds to the story to make that clearer.
It also fixes an issue where we weren't setting the actions to close after hiding blurring the input causing a strange background colour issue with the options cog.
> Add example for renaming via a dropdown action

- lib/TabsNew/TabsActionGroup.js
The title says it all, but heres a longer explanation.
The New Tab button's focus state is behind the fade, so increasing it's z-index is going to place it infront and on top of that fade.
> Increasing the z-index of action groups to appear over the fade

- tailwind.config.js
Using a different colour to the one at the other end of the gradient even if it's transparent causes issues in safari. This PR fixes that by setting both ends of the gradient to the same colour.
Here's some material I found on the issue: https://ambientimpact.com/web/snippets/safari-bug-with-gradients-that-fade-to-transparent
> Fix tab gradients in safari

- lib/Layout/index.js
Our layout was a bit too rigid, it always had the height set the same as the view height. It meant we couldn't use it in other places that have similar layouts.
I originally tried just passing `h-full` into the `className` prop, but this is tailwind and it don't override. Instead I've added a prop that defaults to `true` (So there's no other refactoring), that will set that height to full screen.
> Added a new prop to handle the height of a layout

- lib/ButtonNew/ButtonBase.js
- lib/ButtonNew/common.js
ButtonBase now accepts a function as a child, and it will pass through the styles to that function. That means I could render an `<a>` with the `ButtonTertiary` styles and everything is hunky dory.
> ButtonBase children function

- styles/helpers/_borders.scss
- styles/main.scss
There have been a few designs lately that have required both a 2px blue border (for focus) and a 1px grey border (for blur) on inputs. We have previously had workarounds that involved fun times with padding. I then remembered we fixed it for hierarchy many moons ago. This PR takes that fix and makes a generic class in helpers that can be used elsewhere!
It now also uses the tailwind theme for colours, wahay!
> Creating generic class for pseudo border

- lib/Comment/Comment.js
- lib/Comment/CommentActions.js
- lib/Comment/CommentProvider.js
- lib/Conversation/stories/ConversationBodyForStory.js
This PR fixes a few styling issues with the new conversations refactor;
- Adds borders when there are only 2 comments in a thread
- Fixes border colours on comments
- Fixes story reply count usage (it was showing when there were no hidden replies)
> Conversation styling fixes

- lib/Conversation/Conversation.js
The border for a focused conversation should be `border-blue-primary` and not `border-primary-blue`. Whoops!
> Fixing a conversations border focus

- lib/TabsNew/TabNameForm.js
- tailwind.config.js
Tab asides have gradients that fade the text out when it gets close to the edge. In the process of fixing a browser bug with transparency in Safari, we broke the gradients everywhere 😒 
This PR corrects that by using RGB values in the config and also fixes another issue where the `TabForm` component when active doesn't appear above the gradient.
> Fix tab gradients

- lib/ApprovedLabel/index.js
- package.json
Sets the `defaultActiveColor={false}` prop on a tick icon in the `<ApprovedLabel />` component. It was blue when it should have been green.
Also added David to the contributors on `package.json`. Was literally the first thing I did when I joined GC. @DavidHollins6, you are too humble.
> Turns off defaultActiveColor for approved tick icon in workflow dropdown

- package.json
We previously had a command called `build:watch`, which was supposed to watch our `lib/` dir and `tailwind.config.js` file and build them into the `/dist` directory whenever they changed. However, I broke it with the following:
```javascript
{
"build": "babel lib/ --out-dir dist/lib && babel tailwind.config.js --out-dir dist",
"build:watch": "concurrently \"yarn copy:styles:watch\" \"yarn build --watch\""
}
```
looking at `build:watch`, when we call `yarn build --watch`, it is actually only passing the `--watch` flag to the second babel call. Thus it was only recompiling the tailwindconfig when that changed.
I have created a new command `yarn dev` that actually watches and rebuilds both  `lib/*` and `tailwind.config.js`.
As a bonus, this command adds inline source maps, which means we can …
> Fixes build:watch command, renames it to dev and adds source maps

- lib/Comment/CommentText.js
We should just hide the BottomBlur of a conversation instead of re-rendering it. This was causing issues because it was rendering and pushing other elements around.
`lib/Comment/CommentText.js`
> Hiding conversation blur

- lib/BoundaryClickWatcher/index.js
- lib/Comment/CommentForm.js
In `CommentForm` we call external props before executing internal state changes. This isn't ideal as the external function could unmount the component causing a memory leak.
> Fix leaks in comment forms

- lib/DueDatePicker/index.js
This was using a ref to close the dropdown after selecting or removing a due date. We cant really do that anymore since I've rejigged the dropdown components, plus thats a bit weird too! We're now using the render prop instead. 
Its probably worth coming back and cleaning up this component a bit, anything with `UNSAFE` lifecycle methods is crying out for a refactor. For now I've left it untouched apart from the fix.
> make sure duedate picker closes after selecting or removing a due date

- lib/Comment/CommentText.js
- lib/Conversation/Conversation.js
- tailwind.config.js
There was no difference in background colour between active and inactive conversations. This PR fixes that 👍
> Update the un-active background colour for conversations

- lib/TabsNew/TabAside.js
- lib/TabsNew/TabNameForm.js
It should be further away when inactive.
> Increasing the minus margin for tab labels

- lib/SelectionProvider/index.js
- lib/SelectionProvider/useShiftSelect.js
- lib/index.js
- tests/SelectionProvider/useShiftSelect.spec.js
This is adding a lovely hook to allow shift selection with the SelectionProvider.
We already have this code in a few places in the app, this is just that code but made a little more vague so we can hopefully use it for all the current shift select purposes! There's an upcoming app pr which makes the content hub active/trashed items & hierachy use this hook instead.
> add a useShiftSelect hook

- lib/Comment/CommentForm.js
This PR adds a new prop to CommentForm to have it's submitted button get some tooltip text! You may ask why I did this and not add a permanent tooltip. It's because I'd like to put a shortcut in there, and the amount of code needed to get the short key would make this too much of a hassle to port over to G-UI.
> Adding tooltip text to the comment form submit button

- lib/CheckToggle/index.js
Updates the `<CheckToggle />` label to be a `<label />` tag rather than a `<p />` tag.
Turns out an input can have multiple labels (you'll notice in the file we also have another label that is the actual toggle.
This update was added for targeting `<CheckToggle />` in tests.
> Related to https://github.com/gathercontent/app/pull/3154
> Makes check toggle label a label element

- lib/Field/styles.scss
This PR was originally meant to fix those pesky scroll bars in structure field labels, but I ended up finding a bonus bug while fixing it!
Here is a video of it: https://share.getcloudapp.com/Jru6kwLJ
I fixed this by adding some word breaks to that label. 
NOTE:
Structure fields are the only fields to not be converted to `FieldNew`, I had a look into this and asked around, structure mode is not styled fully in `FieldNew` so would need to have that done before it can be converted.
> Fixing scroll bars in structure fields, fixing word breaks in labels

- lib/ButtonNew/ButtonTertiary/ButtonTertiary.js
When `ButtonTertiary` is used over a UI with colour (e.g. files) the transparent background becomes troublesome. This PR fixes that by adding a default background of white.
I've checked this with @p34ks and all is well 👍  (unless you can think of a reason why not of course)
> Change the default background colour for tertiary buttons

- lib/EditableChoiceInput/index.js
- lib/EditableChoiceInput/stories/EditableChoiceInput.js
- lib/index.js
- stories/index.js
- styles/main.scss
- styles/tailwind-components/index.scss
- styles/tailwind-components/inputs.scss
- tests/EditableChoiceInput/EditableChoiceInput.spec.js
Some fun things here!
We've got a new component which replaces some messy styles in the structure editor for choice field options, and its now up to date with GCDS.
Since I was doing some inputty styling I thought it's a good candidate for our first tailwind component! Any of how I've done this is open to change or up for discussion, its a real finger in the air from me.
The only sort of strange part about it is I've split up the component so we can apply just the border logic if needed. We have a 'text-input' component which applies everything, and then just a 'text-input-border' component. I needed to do this for mu new component and I'm sure there's other places where it may be needed. So its not as clean as we'd like, its a bit iffy about inheriting pseudo styles like :hover etc, so …
> Editable text input component and input tailwind components

- lib/Field/FieldRepeatableControls.js
The repeatable field controls up and down buttons were flickering on hover.
This was being caused by an animation class being inherited by the button from its parent, so on hover it was animating adding the background color, causing the flicker!
This PR updates the parents class name to only animate opacity, meaning the background color is no longer animated 🙏
> Updates Repeatable fields control button to not flicker on hover

- lib/useDeferredList/specs/useDeferredList.spec.js
- lib/useDeferredList/stories/useDeferredListStory.js
- lib/useDeferredList/useDeferredList.js
- package.json
- stories/index.js
- yarn.lock
To optimise the performance of the item editor, we are going to initially load N fields, and when a user scrolls to the bottom of this original set, load in more.
This PR creates the `useDeferredList` custom hook, which will allow us to implement a deferred list pattern.
The hook takes a list, and gives an initial subset of fields, and loads more when `loadItems()` is called.
The custom hook will be used like this:
```javascript
const fields = [...]
const { deferredList, loadItems } = useDeferredList({ 
list: fields, 
initialItemCount: 10, 
numberOfItemsToLoad: 5 
});
return (
<div style={{ overflow-y: 'scroll' }}>
{deferredList.map(field => <Field field={field} />)}
<Waypoint onEnter={loadItems} />
</div>
)
```
when the user scrolls to the waypoint, we will load more fields. …
> Update/add useDeferredList hook

- lib/Field/FieldNew.js
- lib/Field/stories/FieldStory.js
Adds `visible` prop to field new. When toggled, the field fades in and out using opacity.
This is used when we are loading in fields in the Waypoint solution. It felt janky for fields to appear instantly, so this gives it a softer edge!
https://share.getcloudapp.com/X6uNv6Jq
> Adds visible prop to FieldNew

- lib/ColField/styles.scss
- lib/Guideline/index.js
- styles/components/_ui.scss
- tailwind.config.js
- tests/Guideline/Guideline.js
Turns out we need all these custom styles for quill editors within fields. I was umming and ahhing on whether this belonged in the app or here, since they're quite app specific. These live in GUI in the Field styles, so i thought I'd just follow that.
I also needed to pass className over to Guideline and thought I'd do a cheeky refactor while I was there.
> Add styles for field editor, refactor Guideline

- lib/Guideline/index.js
When using this for Quill content we get into a bit of a race condition where we calculate the max height before the content had been populated. Tweaking the use effect fixes this.
> Fix Guidelines max height

- lib/ButtonNew/ButtonIcon/ButtonIcon.js
- lib/ButtonNew/common.js
fixes: https://share.getcloudapp.com/rRu74Jpp
Only base ButtonIcon has this and deals with this prop, so it does not need to be in the shared prop types
> Fix enabled prop warning

- lib/Figure/styles.scss
The figure in the asset field now is separated using the css grid gap, meaning we no longer need the margin!
> Removing the margin from figure

- lib/SearchInput/index.js
Like the title says, we don't want this to happen. 
If we use inline-flex instead of flex the element doesnt take up the entire width it can. I've also added the ability to add classnames, since this always is needed at some point
> Stop SearchInputs from spanning 100% width

- lib/InputConfirmationModal/InputConfirmationModal.js
- lib/InputConfirmationModal/styles.scss
- lib/InputConfirmationModal/tests/InputConfirmationModal.spec.js
- lib/index.js
- stories/components/Modals.js
- styles/components/_ui.scss
This adds a new modal for making people type in a keyword to confirm they do definitely want to do a thing. 
http://g.recordit.co/oStjH8rurV.gif
> Add an InputConfirmationModal component

- lib/useDeferredList/specs/useDeferredList.spec.js
- lib/useDeferredList/useDeferredList.js
Updates the `useDeferredList` hook so that the `deferredList` is updated if the `initialItemCount` argument is changed.
If the `initialItemCount` is updated to a value that is higher than the number of items currently shown, we update the number of items shown to match `initialItemCount`.
This is so we can handle changing `initialItemCount` values.
> Updates useDeferredList

- lib/useDeferredList/specs/useDeferredList.spec.js
- lib/useDeferredList/useDeferredList.js
> ⚠️ Follows on from https://github.com/gathercontent/gather-ui/pull/876
Previously, `useDeferredList` worked as follows:
```javascript
const list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
const { deferredList, loadItems } = useDeferredList({
list,
initialItemCount: 5,
numberOfItemsToLoad: 5
});
console.log(deferredList) // [1,2,3,4,5]
loadItems()
console.log(deferredList) // [1,2,3,4,5,6,7,8,9,10]
```
☝️ This is fine until the list is changed, at which point the deferred version of the list stored in `useDeferredList` state becomes stale!
```javascript
let list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
const { deferredList, loadItems } = useDeferredList({
list,
initialItemCount: 5,
numberOfItemsToLoad: 5
});
console.log(deferredList); // [1,2,3,4,5]
loadItems();
console.log(deferredList); // …
```
> Updates useDeferredList to output itemCount rather than deferredList

- lib/ButtonNew/ButtonIcon/ButtonIcon.js
- lib/ButtonNew/ButtonIcon/ButtonIconContained.js
- lib/ButtonNew/ButtonIcon/styles/buttonIconContained.scss
- lib/ButtonNew/stories/ButtonIcon/ButtonIconStory.js
- lib/index.js
- lib/src/components/files/fileCard/FileCard.js
- lib/src/components/files/fileCard/stories/FileCardStory.js
- lib/src/modules/controls/Control.js
- lib/src/modules/loader/Loader.js
- lib/src/modules/loader/LoaderStory.js
- lib/src/modules/loader/loader.scss
- lib/src/modules/meta/MetaText.js
- lib/src/modules/preview/PreviewImage.js
- lib/src/modules/preview/previewImage.scss
- stories/index.js
- styles/components/_ui.scss
- tailwind.config.js
The loader module can have progress and heading text passed through to it but the styling wasn't there. It was also missing a story to show the states of the new module.
-------
The `FileCard` component uses the `PreviewImage` module which when used in a thumbnail scenario (e.g. in rows) had issues with padding and the fallback touching the edges. This PR adds padding which suits all scenarios. I also added a thumbnail example to the story.
> Improve loader & add FileCard thumbnail example with improved fallback padding.

- lib/ButtonNew/ButtonBase.js
- lib/ButtonNew/styles/buttonBase.scss
- lib/ButtonNew/styles/styles.scss
- styles/components/_ui.scss
I wanted a link to look like a ButtonIcon on the app, we now have a great `button-icon` class I can use, but sadly that doesn't give me everything. This adds the other piece of the puzzle and moves ButtonBase into its own class I can easily grab and use.
> Move button base styles

- lib/LoadingOverlay/index.js
Adds `loadingText` prop to LoadingOverlay so that we can overwrite the default `Loading` text. 
Ronseal!
Companion to https://github.com/gathercontent/app/pull/3479 👫
> Adds `loadingText` prop to LoadingOverlay

- lib/src/components/files/fileCard/FileCardStory.js
- lib/src/modules/preview/PreviewImage.js
- lib/src/modules/preview/previewImage.scss
The preview image module shows a loader before the image has loaded and now we need to be able to show the loader even if the image is present. Here's a GIF showing the option;
> Add prop to manually show the loader 

- lib/DropdownMenu/styles.scss
This fix is best explained in picture form.
BEFORE:
AFTER:
> Removing arbitrary width of dropdown menu name

- lib/TabsNew/TabsScrollShadow.js
We have a shadow on tabs when you are able to scroll to indicate that there are more, the fade for a tab name clashes with it and makes things look a bit nasty. This PR just adds a z-index to the shadow so it is always about the fade, and not part of it.
> Stopping the text fade from touching the shadow on tabs

- lib/src/components/componentWrapper/ComponentWrapper.js
- lib/src/components/componentWrapper/ComponentWrapperBody.js
- lib/src/components/componentWrapper/ComponentWrapperFooter.js
- lib/src/components/componentWrapper/ComponentWrapperHeader/ComponentWrapperHeader.js
- lib/src/components/componentWrapper/ComponentWrapperStory.js
- lib/src/components/componentWrapper/componentWrapper.scss
- styles/tools/_mixins.scss
Just like ColField our ComponentWrapper also needs a selected state. We're using our `before-border` mixin to give our component wrapper sections a lovely thick blue border
> Add a selected state to ComponentWrapper

- lib/DnD/Droppable.js
Adds prop to `<Droppable />` so that we can pass options to the `monitor.isOver(...)` function.
This is so we can pass `{ shallow: true }` so that `isOver` is false if the dragged item is over a child of the target that is also droppable.
> Add isOverOptions prop to Droppable component

- lib/src/prefabs/modalUpload/ModalUploadBody.js
- lib/src/prefabs/modalUpload/modalUpload.scss
- styles/components/_ui.scss
We really should have a max-height for the ModalUpload body prefab.
> Adding a max height to ModalUploadBody

- lib/src/components/dropzone/Dropzone.js
- lib/src/components/modal/modal.scss
Just a couple more dropzone/upload modal fixes:
- There is no longer a focus border on the whole modal when it opens
- There was an issue where the OS file dialog was appearing twice when you clicked the dropzone.
> Fixing a couple of dropzone issues

- lib/FinderNavigation/FinderItem.js
Just as the title says, we don't hook this prop up to anything so it just causes a bit of a rubbish error
> Remove unused and error causing noIndentation prop

- lib/src/components/sidebar/Sidebar.js
- lib/src/components/sidebar/SidebarDescription.js
- lib/src/components/sidebar/SidebarHeading.js
- lib/src/components/sidebar/SidebarSectionHead.js
- lib/src/components/sidebar/SidebarSectionToggle.js
- lib/src/components/sidebar/SidebarStory.js
- lib/src/components/sidebar/sidebar.scss
In the recent #947 PR we added a new sidebar component. This PR alters the work to make it easier to work with by;
- adding a missing `SidebarDescription` (recently added in the designs)
- making the show toggle composable as we need to alter the button text per instance
- making the section heading area perform better alongside the toggle (so it doesn't wrap)
To achieve some of this I had to abstract some things into their own component but the functionality is all the same 👍
> Sidebar component edits

- lib/src/components/sidebar/SidebarHeader.js
- lib/src/components/sidebar/SidebarSection.js
- lib/src/components/sidebar/SidebarStory.js
- lib/src/components/sidebar/sidebar.scss
We'd like to be able to close the sidebar. So the header of it now accepts an onClose function which renders a lovely cross icon button!
> Adding a close button to the sidebar header

- lib/ShortcutTrigger/index.js
- lib/src/modules/input/Input.js
- tests/ShortcutTrigger/index.js
The title says it all. We check the event to see if it was from a text input, if it is we do nothing.
> Prevent ShortCutTrigger from triggering in text fields

- lib/ColField/ColField.js
- lib/ColField/stories/ColFieldStory.js
- lib/src/components/componentWrapper/ComponentWrapper.js
- lib/src/components/componentWrapper/ComponentWrapperBody.js
- lib/src/components/componentWrapper/ComponentWrapperFooter.js
- lib/src/components/componentWrapper/ComponentWrapperHeader/ComponentWrapperHeader.js
- lib/src/components/componentWrapper/ComponentWrapperStory.js
- lib/src/components/componentWrapper/componentWrapper.scss
When hovering over repeat buttons for fields/components we needed a 1px blue border style, enter our new prop `isHovered`. We already had a `hovered` prop for some `ComponentWrapper` components, but as we only use that for dnd i've renamed it to `draggedOver`, having a `isHovered` and `hovered` prop felt a bit icky!
> add isHovered prop to ColField and ComponentWrapper

- lib/DnD/Droppable.js
We do quite a lot in our hover handlers on app, which causes some really slow and sluggish dnd behaviour for people on struggling computers. The on hover event fires an awful lot, so adding a throttle will reduce the strain and make dnd a bit nippier.
> add throttle to hover handler

- lib/ConfirmationDropdown/ConfirmationDropdownContent.js
- lib/Dropdown/DropdownContent.js
- lib/Dropdown/index.js
- stories/components/Dropdown.js
When conditionally rendering the dropdown content a race condition happens when auto positioning the dropdown content. It tries to grab the element and its bounds before its rendered, stopping auto positioning from working and keeping the dropdown off screen. 
I've refactored the component and tweaked when we calculate styles to stop this from happening. 
`lib/Dropdown/DropdownContent.js`
> Refactor & fix race condition for auto positioned dropdown content

- lib/src/modules/person/Person.js
Whoops, there needs to be a default value for the new `highlightText` prop!
> Adding a default highlight prop to the person component

- lib/src/modules/input/InputWithMentions.js
The title says it all. We would like to submit the `InputWIthMentions` with cmd+enter.
> Adding a shortcut trigger for submitting an input with mentions

- lib/DropdownMenu/index.js
- lib/DropdownMenu/styles.scss
`useEffect` does some caching and because event listener is only set up on mount while `showItems` is false, it then always thinks its false every time that event is fired. 
Changing it so the event listener gets set up when `showItems` is true solves the problem, and as a nice side effect we're not needlessly setting up event listeners before someones even interacted with the dropdown
> Fix DropdownMenu not closing after clicking on item or clicking outside of dropdown

- lib/TopBar/index.js
After refactoring `Grid` from bootstrap in #1038, padding collapsing that overrode bootstrap styles were being negated due to specificity. 
The only one I have managed to find is padding so I added a tailwind utility class to tackle this specific issue.
> Fix collapse padding on the TopBar component

- lib/Form/styles.scss
- lib/src/modules/selectionControls/SelectionControlsStory.js
When we use a `RadioInput` or `CheckboxInput` inside of a `.form`, we were setting the `width: 100%`
This PR fixes that.
NOTE: I had to commit this with `--no-verify` because the eslint and prettier are wildly off, see #1048
> Don't set radio/checkbox input width to 100%

- lib/src/components/sidebar/SidebarFooter.js
- lib/src/components/sidebar/SidebarStory.js
- lib/src/components/sidebar/sidebar.scss
This means we can more easily custimise the layout of the children, for
example having a help button that aligns to the left of the footer
> Sidebar Footer now uses justify-end instead of a nested div with ml-auto

- lib/src/modules/optionMenuItem/option-menu-item.scss
We need to full width the text in an option menu item, this is so the fade is at the end of its container. This same fade issue occurs on both usages of `OptionMenuItem`.
> Fixing fade cutting into option menu items

- lib/ButtonNew/ButtonIcon/styles/buttonIconDanger.scss
its the only button icon with a background colour on a non interacted state, so lets get rid
> remove bg colour from ButtonIconDanger

- lib/src/prefabs/files/fileCard/FileCard.js
- lib/src/prefabs/files/fileCard/FileCardStory.js
`preview` shouldn't be required in `FileCard`s. Even the story shows this via
```
<FileCard className="h-full" innerClassName="h-full">
<Loader size="sm" className="h-full" />
</FileCard>
```
> Remove required prop and update story

- lib/TopBar/styles.scss
- lib/index.js
- lib/src/modules/Button/ButtonIcon/ButtonIconWhite.js
- lib/src/modules/Button/ButtonIcon/styles/buttonIcon.scss
- lib/src/modules/Button/ButtonIcon/styles/buttonIconWhite.scss
- lib/src/modules/Button/stories/ButtonIcon/ButtonIcon.stories.js
TopBar dark mode icons no longer have their colour set by CSS.
A new component, ButtonIconWhite has been added to allow us to use white button icons.
ButtonIconWhite has been added to the button icon story.
(https://trello.com/c/8fhSwIVx/2379-regular-icon-colour-is-incorrect-on-disabled-button-states)
https://github.com/gathercontent/app/pull/4509
> TopBar icon colours

- lib/BlankSlate/styles.scss
Fixes secondary button height inside blank slates as they were displaying slightly smaller then the primary button next to them.
> fix secondary button height in blank slates

- lib/src/modules/calendar/calendar.scss
Ensure that on the due date calendar, today is only highlighted if the current month is visible.
https://trello.com/c/RXEcbBZ8/2554-regular-current-day-showing-on-previous-following-months-when-no-number-visible
> ensure that today is not highlighted when its off the calendar

- lib/Navigation/styles.scss
Removes an ugly underline hover effect on tab navigation items.
(https://trello.com/c/vGcyB5cf/2669-new-trial-snags)
> remove underline hover effect on tab navigation items

- lib/Avatar/AvatarWithPopover.js
- lib/Avatar/stories/Avatar.stories.js
- lib/Avatar/styles.scss
`AvatarWithPopover` has been updated to use Tippy rather than the `Dropdown` component.
With the `Dropdown` component, when hovering from the bottom of the trigger, the dropdown content overlays the trigger and causes the mouse to 'leave' the trigger, hiding the content. Using Tippy and a standard tooltip stops this from happening.
There is a slight drawback in that the avatar component loses some functionality to allow it to have links or menu items as the dropdown content, but this is never used inside the app and I think it's worth removing unused functionality to fix a bug. It also massively simplifies the component.
(https://trello.com/c/CcQVR0my/2812-presence-avatar-tooltips-flash-and-disappear)
> update AvatarWithPopover component to use Tippy

- lib/Avatar/stories/Avatar.stories.js
- lib/Avatar/styles.scss
- lib/ParticipantInfo/index.js
- lib/ParticipantInfo/styles.scss
Styles the `ParticipantInfo` like our original tooltip component and removes the 'assigned' pillbox.
(https://trello.com/c/BUtSyCGq/2832-style-participantinfo-like-a-tooltip)
https://www.figma.com/file/rKBbivLiVBDi1IPimZg7Lh/GUI---Components?node-id=488%3A2615
> update styling of participant info to be like tooltip

- lib/Comment/CommentForm.js
When searching for users to tag in a comment, the search term is now converted to lower case before searching for a user.
(https://trello.com/c/uiDBRBKU/2919-regular-finding-people-to-mention-is-case-sensitive)
> make search term lowercase so search not case sensitive

- lib/src/modules/preview/previewImage.scss
- lib/src/prefabs/files/fileCard/FileCard.stories.js
This ended up being really easy, as its a background image its just a case of using contain rather than cover for background size 👌
http://g.recordit.co/6eH1VBpSvi.gif
> make preview image contain the image, not cover

- lib/StatusIndicator/styles.scss
Reverts gathercontent/gather-ui#1127 as the style is not actually needed.
> Revert "reduce font weight in bulk action dropdown"

- .eslintrc.json
Its not flagging up the warning locally, or for previous ci. return is consistent so i think linter is misbehaving. setting it to a warning for now just so linting will pass on publish action.
> make a lint error a warning

- lib/EditableTextWrapper/EditableTextWrapperText.js
When an editable text wrapper edit button is clicked, events now no longer propagate to the parent. This should stop an item row being selected when the edit name button is clicked.
(https://trello.com/c/v6Ib2Acm/241-small-improvements-to-item-creation-ux)
> stop propagation when editable text edit button clicked

- lib/Dropdown/styles.scss
Chevron was facing the wrong was as it was reading a higher 'is-active' class - https://trello.com/c/vBI8PfGp/4165-multiple-workflow-snags-v2
> More specific CSS chevron styles for active state

- lib/src/modules/Button/ButtonIcon/styles/buttonIconBase.scss
Remove the active styling as it is handled in a separate block, and remove the focus styling as it is causing active buttons to not have active styling until the user clicks somewhere else.
> GC-530 remove focus and active styling from ButtonIcon

- lib/DueDatePicker/DueDateLabel.js
The text that is returned from the API already contains `in`, so the component does not need to render it.
> GC-557 remove in from DueDateLabel text

- lib/Avatar/styles.scss
Large and extra large avatars had no CSS to apply the correct font sizes, this PR adds them in.
> FSB-5245 add large and xl font sizing to avatars

- lib/src/modules/Button/ButtonIcon/styles/buttonIconBase.scss
Its currently impossible to tell if a ButtonIcon has focus when using keyboard controls, this fixes it
> add focus styles to button icon

- lib/src/components/form/FormInput.js
- lib/src/modules/Button/ButtonLink/ButtonLink.js
- lib/src/modules/input/Input.js
As part of GC-857 we need to swap dom queries for ref hooks for best practice. Problem is, we don't have access to the refs from within gather-ui so we need to expose the refs via prop drilling.
We tried react's forwardRefs but it seems a little over-engineered for this small task.
[_Links that relate to the PR (Trello, Figma etc.)_](https://bynder.atlassian.net/browse/GC-857)
> GC-857 - Can we use React refs instead of DOM queries

- lib/Pill/PillBase.js
- lib/Pill/common.js
- lib/Pill/stories/Pill.stories.js
Related to [this PR](https://github.com/Bynder/gathercontent-mono/pull/217) on mono.
Badges and pills seem to be interchangeable on gather-ui, whereas on mono they are separate. Because of this I have had to go with the size `xxs` as `xs` already exists and is in use.
> Adding xxs pill

- lib/Icon/styles.scss
Following a previous PR the max-width on icons is messing some of them up.
📹 - https://capture.dropbox.com/GTqKkiC6uDUJ6v0v
From this ticket - https://bynder.atlassian.net/jira/software/c/projects/GC/boards/505?modal=detail&selectedIssue=GC-888&assignee=636a892ad3f3a7ad527b2191
> GC-986 - Fixing icon sizes

- lib/Icon/styles.scss
Removing the text colour property from the warning icon CSS, as this allows the correct icon colour to cascade from the parent element.
> remove the text colour from warning icon

- lib/Dropdown/DropdownAction.js
- lib/src/modules/Button/ButtonBase.js
Fixing some issues that are causing spammy console logs and actual issues potentially getting missed
#BrokenWindows
> GC-1083 - Fix console log spam in item editor

- lib/CollectionsTable/styles.scss
📹 https://share.getcloudapp.com/lluX6BNY
Added a max width on the text container so the pencil icon fits.
> GC-1351 - I can't see the rename icon on items with a long name

- package.json
Fixes the issue you might get when running the build process and typescript is unable to generate new type definitions
> :sparkles: Delete existing dist folder on build

- lib/TooltipWrapper/tippystyles.scss
- stories/components/TooltipWrapper.stories.tsx
[Selection toolbar tooltips are too far away. (After further inspection, this is true across the app)](https://bynder.atlassian.net/browse/GC-1793)
Closing the gap of the tooltips. There doesn't appear to be a way to do this via the [plugin](https://atomiks.github.io/tippyjs/#placements), so I styled with CSS. Some formatting styles snuck in there too.
> closing gap from tooltip

- lib/Dropdown/DropdownTrigger.tsx
https://bynder.atlassian.net/browse/GC-2006
We found a bug where the translations menu and the change tone menu for AI transformation options clash. This PR fixes the issue by making sure the menus hide when the mouse is no longer hovering on them. This way, we won't have multiple menus open and they won't overlap.
> :bug: Ensure we close hover menus when we're no longer hovering

- lib/ColField/tests/ColField.spec.tsx
- lib/InputConfirmationModal/tests/InputConfirmationModal.spec.tsx
- lib/PillInput/tests/PillInput.spec.tsx
- lib/SelectionBar/specs/SelectionBar.spec.tsx
- lib/Windowing/tests/Windowing.spec.tsx
- lib/src/modules/input/InputWithMentions.tsx
Newer ReactMentions have changed what props you need to pass to what component, this fixes that.
I also had errors in these tests when linking locally, so i've just fixed the imports for those too
> fix ReactMentions props and fix tests that stop local linting

- lib/Comment/CommentForm.tsx
Some formatting changes in here, the only real change is `tabbable="false"` to the tooltip wrapper
> Remove tabbable form tooltip

- lib/Resizable/index.tsx
Resolves the issue where resizing the browser to a size smaller than that of the resized element would make the page unusable because the resized element consumes the screen.
https://www.loom.com/share/93fd6e6d0e034227b95c71ab7a5979ba
> 🐛  GC-1464 - On window resize ensure resized element shrinks too

- lib/Notification/blip/NotificationBlip.tsx
- lib/Notification/blip/styles/NotificationBlip.scss
- lib/index.ts
- stories/components/NotificationBlip.stories.tsx
0-day patch 😬 
- Rework the notification blip to take children instead of being used as a child
- Actually export the notification blip so it can be used
> GC-3155 Rework the notification blip to take children

- lib/LoadingOverlay/index.tsx
- lib/LoadingOverlay/styles.scss
- lib/src/modules/loader/Loader.stories.tsx
- lib/src/modules/loader/Loader.tsx
- lib/src/modules/loader/loader.scss
- stories/components/LoadingOverlay.stories.tsx
Add a new size to Loader which we then use in LoadingOverlay and an option to use the Loader (spinner) instead of the speech bubble
> GC-3219 add the option to use a spinner in the loading overlay component

- package-lock.json
💬 Description
npm audit fix resolves the babel traverse vulnerability by incrimenting to to the latest safe patch version of "7.23.2",
> GC-3079 - Critical vulnerability around @babel/traverse

- lib/src/modules/input/Input.tsx
This should resolve the type conflict between our custom size prop and the native HTML input attribute - as whitnessed in this CI process https://github.com/Bynder/gathercontent-gather-ui/pull/1318#discussion_r1380081027.
> 🏷️ Prevent collision with native HTML input size property

- lib/Notification/blip/NotificationBlip.tsx
- stories/components/NotificationBlip.stories.tsx
- Added visible prop to Notification Blip, controlling the visibility using the Tailwind opacity class
- Updated the Notification Blip story accordingly
Relates to https://github.com/Bynder/gathercontent-csr/pull/5591.
> GC-3452 Control Notification Blip visibility with visible prop

- lib/src/modules/Button/ButtonTertiary/styles/buttonTertiary.scss
Not a gui- class issue, but transparent background styles dont work on anything but a plain background
> GC-3644 fix button tertiary state styles for non white backgrounds

- lib/Comment/CommentForm.tsx
- lib/UserSearch/UserSearchList.tsx
- stories/components/UserSearch.stories.tsx
> :sparkles: Add pending state to comment form and user search

- lib/Dropdown/styles.scss
https://bynder.atlassian.net/browse/GC-3829
"Strange styling issue. Some menu items are underlined on hover, others aren’t. The example shown is the item menu.
Menu items should not be underlined on hover."
> 🩹GC-3829 Menu items being underlined on hover

- lib/Comment/CommentResolveButton.tsx
- lib/Comment/styles.scss
The tailwind class applied inline in the component only applies to the span and doesn't filter down to the SVGs path elements.
Doing this via SCSS ensures the correct colour is applied to the whole SVG.
I'm unsure if this has always been incorrect, or if the changes happened as part of the mono/gui tailwind clash resolutions
> GC-3786 Wrong icon colour when resolving conversations

- CODEOWNERS
- README.md
🥫 
Preview: https://github.com/Bynder/gathercontent-gather-ui/blob/docs/GC-3914/README.md
> [GC-3914] Gather UI README rebuild

- lib/Avatar/AvatarWithPopover.tsx
- lib/Avatar/stories/Avatar.stories.tsx
- lib/ParticipantInfo/index.tsx
- stories/components/ParticipantInfo.stories.tsx
This UI work to completes https://bynder.atlassian.net/browse/GC-3901
Basically it just adds the pending text and bullet to the beginning of the "email" (the email can actually be the user email, "Set By Workflow" or "Remove")
The logic in CSR was duplicated and getting silly, so instead I reverted those changes and we can just let the actually components decide whether to add "Pending" or not to the UI.
Is required by https://github.com/Bynder/gathercontent-csr/pull/5676
I also added the correct typing for ParticipantInfo
> :sparkles: Render pending ui within avatar popover text and participants

- lib/Comment/CommentForm.tsx
- Pass user ID back with comment form `onMention` function call
> [!NOTE]
> Required by https://github.com/Bynder/gathercontent-csr/pull/5693.
> GC-3893 Pass user ID back with comment form `onMention` function call

- .github/workflows/npm-publish.yml
As part of the Bynder adoption of GitHub Actions they have reviewed our action usage and found a few actions we don't specify a specific version which could mean those actions could get comprised and we would pull in the comprised action straight away.
> [GC-4172] Move all GitHub Actions across to fixed versions
